/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.login;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import lbfinance.serverConnector.ServerConnector;
import lbfinancecommon.controller.UserController;
import lbfinancecommon.model.User;
import view.main.MainForm;

/**
 *
 * @author Hasitha
 */
public class LoginForm extends javax.swing.JFrame {

    private int tryOuts = 0;
    private Timer t;
    public static LoginForm thisForm;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        thisForm = this;
        ImageIcon icon = new ImageIcon(new ImageIcon(".\\src\\lbfinance\\images\\LOGIN BACKGROUND New2.png").getImage().getScaledInstance(loginBackgroundLabel.getWidth(), loginBackgroundLabel.getHeight(), Image.SCALE_SMOOTH));
        loginBackgroundLabel.setIcon(icon);
        userNameTextField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane = new javax.swing.JLayeredPane();
        userNameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        logInButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        loginBackgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameTextField.setBackground(new java.awt.Color(0, 0, 0));
        userNameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        userNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        userNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });
        userNameTextField.setBounds(260, 270, 260, 30);
        jLayeredPane.add(userNameTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        passwordField.setBackground(new java.awt.Color(0, 0, 0));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passwordField.setEnabled(false);
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.setBounds(260, 320, 260, 30);
        jLayeredPane.add(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        logInButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        logInButton.setText("Log In");
        logInButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logInButton.setEnabled(false);
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        logInButton.setBounds(443, 410, 80, 30);
        jLayeredPane.add(logInButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        warningLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        warningLabel.setBounds(140, 224, 380, 40);
        jLayeredPane.add(warningLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginBackgroundLabel.setBounds(0, 0, 1370, 770);
        jLayeredPane.add(loginBackgroundLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        if (userNameTextField.getText() != null) {
            passwordField.setEnabled(true);
            passwordField.requestFocus();
        }
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        try {
            if (tryOuts < 2) {
                String userName = userNameTextField.getText();
                char[] ch = passwordField.getPassword();
                String password = new String(ch);
                tryOuts = tryOuts + 1;

                User user = new User(userName, password, WIDTH);

                ServerConnector serverConnector = ServerConnector.getServerConnector();
                UserController userController = serverConnector.getUserController();

                int privilege = userController.searchUser(user);

                if (privilege == 1) {
                    thisForm.setVisible(false);
                    new MainForm().setVisible(true);
                    MainForm.setUserName(userName);
                } else if (privilege == 2) {
                    thisForm.setVisible(false);
                    new MainForm().setVisible(true);
                    MainForm.setUserName(userName);
                } else if (privilege == -1) {
                    warningLabel.setForeground(Color.ORANGE);
                    warningLabel.setText("<html>Invalid username or password. <br>Remaining Attempt : " + (3 - tryOuts)+"</html>");
                    userNameTextField.setText(null);
                    passwordField.setText(null);
                    passwordField.setEnabled(false);
                    logInButton.setEnabled(false);
                    userNameTextField.requestFocus();
                }
            } else {
                userNameTextField.setText(null);
                passwordField.setText(null);
                userNameTextField.setEnabled(false);
                passwordField.setEnabled(false);
                warningLabel.setText("<html>Invalid username or password. <br>Remaining Attempt : 0</html>");
                t = new Timer(1000, new ActionListener() {
                    int i = 0;

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (i == 15) {
                            thisForm.setVisible(false);
                            new LoginForm().setVisible(true);
                            t.stop();
                        }
                        System.out.println("Warning : Reached limit of attempts. Please wait " + (15 - i) + "s to reset the system.");
                        warningLabel.setForeground(Color.ORANGE);
                        warningLabel.setText("<html>Warning : Reached limit of attempts. <br>Please wait " + (15 - i) + "s to reset the system.</html>");
                        i++;
                    }
                });
                t.start();
            }
        } catch (NotBoundException | MalformedURLException | RemoteException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logInButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        logInButton.setEnabled(true);
        logInButton.doClick();
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JButton logInButton;
    private javax.swing.JLabel loginBackgroundLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
