/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.leasedVehicle;

import java.awt.Color;
import java.awt.Image;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lbfinance.serverConnector.ServerConnector;
import lbfinancecommon.controller.VehicleCategoryController;
import lbfinancecommon.model.VehicleCategory;

/**
 *
 * @author Hasitha
 */
public class NewVehicleCategoryForm extends javax.swing.JFrame {

    /**
     * Creates new form NewVehicleCategoryForm
     */
    public NewVehicleCategoryForm() {
        initComponents();
        setLocationRelativeTo(null);
        vehicleCategoryIdTextField.requestFocus();

        ImageIcon icon = new ImageIcon(new ImageIcon(".\\src\\lbfinance\\images\\abstract_bg4To3.png").getImage().getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), Image.SCALE_SMOOTH));
        backgroundLabel.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        vehicleCategoryIdLabel = new javax.swing.JLabel();
        vehicleCategoryIdTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descriptionTextArea.setBackground(new java.awt.Color(233, 231, 231));
        descriptionTextArea.setColumns(5);
        descriptionTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descriptionTextArea.setRows(10);
        descriptionTextArea.setEnabled(false);
        jScrollPane1.setViewportView(descriptionTextArea);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 360, 100));

        descriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descriptionLabel.setText("Description :");
        jLayeredPane1.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        vehicleCategoryIdLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vehicleCategoryIdLabel.setText("Vehicle Category ID :");
        jLayeredPane1.add(vehicleCategoryIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        vehicleCategoryIdTextField.setBackground(new java.awt.Color(233, 231, 231));
        vehicleCategoryIdTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vehicleCategoryIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleCategoryIdTextFieldActionPerformed(evt);
            }
        });
        jLayeredPane1.add(vehicleCategoryIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 85, 30));

        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 87, 35));
        jLayeredPane1.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 260, 20));
        jLayeredPane1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicleCategoryIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleCategoryIdTextFieldActionPerformed
        if (!vehicleCategoryIdTextField.getText().equals("")) {
            descriptionTextArea.setEnabled(true);
            descriptionTextArea.setText(null);
            descriptionTextArea.requestFocus();
        }
    }//GEN-LAST:event_vehicleCategoryIdTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String vehicleCategoryId = vehicleCategoryIdTextField.getText();
        String description = descriptionTextArea.getText();
        if (!description.equals("")) {
            try {
                ServerConnector serverConnector = ServerConnector.getServerConnector();
                VehicleCategoryController vehicleCategoryController = serverConnector.getVehicleCategoryController();

                VehicleCategory vehicleCategory = new VehicleCategory(vehicleCategoryId, description);
                boolean res = vehicleCategoryController.addVehicleCategory(vehicleCategory);

                if (res) {
                    JOptionPane.showMessageDialog(this, "New Vehicle Category successfully added.", "Message", JOptionPane.PLAIN_MESSAGE);
                    vehicleCategoryIdTextField.setText(null);
                    descriptionTextArea.setText(null);
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add new Category.", "Message", JOptionPane.PLAIN_MESSAGE);
                }
            } catch (NotBoundException | MalformedURLException | RemoteException | ClassNotFoundException | SQLException ex) {
                Logger.getLogger(NewVehicleCategoryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            warningLabel.setText("Please add a description.");
            warningLabel.setForeground(Color.ORANGE);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewVehicleCategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewVehicleCategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewVehicleCategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewVehicleCategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewVehicleCategoryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel vehicleCategoryIdLabel;
    private javax.swing.JTextField vehicleCategoryIdTextField;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
