/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.leasedVehicle;

import java.awt.Image;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import lbfinance.serverConnector.ServerConnector;
import lbfinancecommon.controller.VehicleCategoryController;
import lbfinancecommon.model.VehicleCategory;

/**
 *
 * @author Hasitha
 */
public class SearchVehicleCategory extends javax.swing.JFrame {

    /**
     * Creates new form SearchVehicleCategory
     */
    public SearchVehicleCategory() {
        initComponents();
        vehicleCategoryComboBox.requestFocus();

        ImageIcon icon = new ImageIcon(new ImageIcon(".\\src\\lbfinance\\images\\abstract_bg4To3.png").getImage().getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), Image.SCALE_SMOOTH));
        backgroundLabel.setIcon(icon);
        try {
            ServerConnector serverConnector = ServerConnector.getServerConnector();
            VehicleCategoryController vehicleCategoryController = serverConnector.getVehicleCategoryController();
            ArrayList<String> categories = vehicleCategoryController.getAllCategoryIds();
            
            for(String c : categories){
                vehicleCategoryComboBox.addItem(c);
            }
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SearchVehicleCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        vehicleCategoryIdLabel = new javax.swing.JLabel();
        vehicleCategoryComboBox = new javax.swing.JComboBox();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vehicleCategoryIdLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vehicleCategoryIdLabel.setText("Vehicle Category ID :");
        jLayeredPane1.add(vehicleCategoryIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, -1, -1));

        vehicleCategoryComboBox.setBackground(new java.awt.Color(231, 231, 231));
        vehicleCategoryComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vehicleCategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleCategoryComboBoxActionPerformed(evt);
            }
        });
        jLayeredPane1.add(vehicleCategoryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 80, -1));

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 87, -1));

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setBackground(new java.awt.Color(231, 231, 231));
        descriptionTextArea.setColumns(1);
        descriptionTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descriptionTextArea.setRows(5);
        descriptionTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descriptionTextArea);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 138, 360, 83));

        descriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descriptionLabel.setText("Description :");
        jLayeredPane1.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, -1, -1));
        jLayeredPane1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            ServerConnector serverConnector = ServerConnector.getServerConnector();
            VehicleCategoryController vehicleCategoryController = serverConnector.getVehicleCategoryController();
            
            String searchText = (String) vehicleCategoryComboBox.getSelectedItem();
            VehicleCategory vehicleCategory = vehicleCategoryController.searchCategory(searchText);
            
            descriptionTextArea.setText(vehicleCategory.getDescription());
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SearchVehicleCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void vehicleCategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleCategoryComboBoxActionPerformed
        try {
            ServerConnector serverConnector = ServerConnector.getServerConnector();
            VehicleCategoryController vehicleCategoryController = serverConnector.getVehicleCategoryController();
            
            String searchText = (String) vehicleCategoryComboBox.getSelectedItem();
            VehicleCategory vehicleCategory = vehicleCategoryController.searchCategory(searchText);
            
            descriptionTextArea.setText(vehicleCategory.getDescription());
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SearchVehicleCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vehicleCategoryComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchVehicleCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchVehicleCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchVehicleCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchVehicleCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchVehicleCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox vehicleCategoryComboBox;
    private javax.swing.JLabel vehicleCategoryIdLabel;
    // End of variables declaration//GEN-END:variables
}
