/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.leasedVehicle;

import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import lbfinance.serverConnector.ServerConnector;
import lbfinancecommon.controller.LeasedVehicleController;
import lbfinancecommon.model.LeasedVehicle;

/**
 *
 * @author Sameera
 */
public class UpdateLeasedVehicleWithSearchForm extends javax.swing.JDialog {

    private static String searchBy;
    private static String searchColumn;
    private static String searchKey;

    /**
     * Creates new form LeasedVehicleForm
     */
    public UpdateLeasedVehicleWithSearchForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        modelNameLabel = new javax.swing.JLabel();
        cahssisNoLabel = new javax.swing.JLabel();
        registrationNoLabel = new javax.swing.JLabel();
        EngineNo = new javax.swing.JLabel();
        manufacturedYearLabel = new javax.swing.JLabel();
        estimatedPriceLabel = new javax.swing.JLabel();
        licensedDateLabel = new javax.swing.JLabel();
        searchByLabel = new javax.swing.JLabel();
        colourOfVehicleLabel = new javax.swing.JLabel();
        fuelUseLabel = new javax.swing.JLabel();
        cylinderCapacityLabel = new javax.swing.JLabel();
        wheelBaseLabel = new javax.swing.JLabel();
        colourOfVehicleTextField = new javax.swing.JTextField();
        modelNameTextField = new javax.swing.JTextField();
        chassisNoTextField = new javax.swing.JTextField();
        registrationNoTextField = new javax.swing.JTextField();
        engineNoTextField = new javax.swing.JTextField();
        licensedFormattedTextField = new javax.swing.JFormattedTextField();
        manufacturedYearFormattedTextField = new javax.swing.JFormattedTextField();
        estimatedPriceFormattedTextField = new javax.swing.JFormattedTextField();
        fuelUseFormattedTextField = new javax.swing.JFormattedTextField();
        cylinderCapacityFormattedTextField = new javax.swing.JFormattedTextField();
        wheelBaseFormattedTextField = new javax.swing.JFormattedTextField();
        uploadVehiclePhotoButton = new javax.swing.JButton();
        deletePhotoButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        searchComboBox = new javax.swing.JComboBox();
        searchButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        pictureLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        modelNameLabel.setText("Model & Name :");
        modelNameLabel.setBounds(20, 180, 100, 14);
        jLayeredPane1.add(modelNameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cahssisNoLabel.setText("Chassis No :");
        cahssisNoLabel.setBounds(20, 210, 100, 14);
        jLayeredPane1.add(cahssisNoLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        registrationNoLabel.setText("Registration No :");
        registrationNoLabel.setBounds(20, 240, 100, 14);
        jLayeredPane1.add(registrationNoLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        EngineNo.setText("Engine No :");
        EngineNo.setBounds(20, 270, 100, 14);
        jLayeredPane1.add(EngineNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        manufacturedYearLabel.setText("Manufactured Year :");
        manufacturedYearLabel.setBounds(20, 300, 100, 14);
        jLayeredPane1.add(manufacturedYearLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        estimatedPriceLabel.setText("Estimated Price :");
        estimatedPriceLabel.setBounds(20, 330, 100, 14);
        jLayeredPane1.add(estimatedPriceLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        licensedDateLabel.setText("Licened Date :");
        licensedDateLabel.setBounds(20, 480, 100, 14);
        jLayeredPane1.add(licensedDateLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        searchByLabel.setText("Search By :");
        searchByLabel.setBounds(30, 70, 90, 14);
        jLayeredPane1.add(searchByLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        colourOfVehicleLabel.setText("Colour Of Vehicle :");
        colourOfVehicleLabel.setBounds(20, 360, 100, 14);
        jLayeredPane1.add(colourOfVehicleLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fuelUseLabel.setText("Fuel Use :");
        fuelUseLabel.setBounds(20, 390, 100, 14);
        jLayeredPane1.add(fuelUseLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cylinderCapacityLabel.setText("Cylinder Capacity :");
        cylinderCapacityLabel.setBounds(20, 420, 100, 14);
        jLayeredPane1.add(cylinderCapacityLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wheelBaseLabel.setText("Wheel Base :");
        wheelBaseLabel.setBounds(20, 450, 100, 14);
        jLayeredPane1.add(wheelBaseLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        colourOfVehicleTextField.setBounds(130, 360, 140, 20);
        jLayeredPane1.add(colourOfVehicleTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        modelNameTextField.setEditable(false);
        modelNameTextField.setBounds(130, 180, 180, 20);
        jLayeredPane1.add(modelNameTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        chassisNoTextField.setEditable(false);
        chassisNoTextField.setBounds(130, 210, 180, 20);
        jLayeredPane1.add(chassisNoTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        registrationNoTextField.setBounds(130, 240, 180, 20);
        jLayeredPane1.add(registrationNoTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        engineNoTextField.setBounds(130, 270, 180, 20);
        jLayeredPane1.add(engineNoTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        licensedFormattedTextField.setEditable(false);
        licensedFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        licensedFormattedTextField.setBounds(130, 480, 109, 20);
        jLayeredPane1.add(licensedFormattedTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        manufacturedYearFormattedTextField.setEditable(false);
        manufacturedYearFormattedTextField.setBounds(130, 300, 110, 20);
        jLayeredPane1.add(manufacturedYearFormattedTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        estimatedPriceFormattedTextField.setEditable(false);
        estimatedPriceFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        estimatedPriceFormattedTextField.setBounds(130, 330, 109, 20);
        jLayeredPane1.add(estimatedPriceFormattedTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fuelUseFormattedTextField.setEditable(false);
        fuelUseFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.###km"))));
        fuelUseFormattedTextField.setBounds(130, 390, 109, 20);
        jLayeredPane1.add(fuelUseFormattedTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cylinderCapacityFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        cylinderCapacityFormattedTextField.setBounds(130, 420, 109, 20);
        jLayeredPane1.add(cylinderCapacityFormattedTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        wheelBaseFormattedTextField.setEditable(false);
        wheelBaseFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        wheelBaseFormattedTextField.setBounds(130, 450, 109, 20);
        jLayeredPane1.add(wheelBaseFormattedTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        uploadVehiclePhotoButton.setText("Upload Vehicle Photo");
        uploadVehiclePhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadVehiclePhotoButtonActionPerformed(evt);
            }
        });
        uploadVehiclePhotoButton.setBounds(350, 360, 190, 23);
        jLayeredPane1.add(uploadVehiclePhotoButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        deletePhotoButton.setText("Delete Photo");
        deletePhotoButton.setBounds(350, 390, 190, 23);
        jLayeredPane1.add(deletePhotoButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        updateButton.setBounds(410, 500, 130, 40);
        jLayeredPane1.add(updateButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        searchComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Registration No", "Engine No", "Chassis No" }));
        searchComboBox.setBounds(110, 70, 180, 20);
        jLayeredPane1.add(searchComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        searchButton.setBounds(360, 110, 80, 23);
        jLayeredPane1.add(searchButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        searchTextField.setBounds(30, 110, 320, 20);
        jLayeredPane1.add(searchTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pictureLabel.setBounds(350, 150, 188, 188);
        jLayeredPane1.add(pictureLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            String registrationNo = registrationNoTextField.getText();
            String engineNo = engineNoTextField.getText();
            String colour = colourOfVehicleTextField.getText();
            String cylinderCapacity = cylinderCapacityFormattedTextField.getText();
            double cylinderCapacityD = Double.parseDouble(cylinderCapacity);
            
            LeasedVehicle leasedVehicle = new LeasedVehicle();
            leasedVehicle.setRegistrationNo(registrationNo);
            leasedVehicle.setEngineNo(engineNo);
            leasedVehicle.setColour(colour);
            leasedVehicle.setCylinderCapacity(cylinderCapacityD);
            
            ServerConnector serverConnector = ServerConnector.getServerConnector();
            LeasedVehicleController leasedVehicleController = serverConnector.getLeasedVehicleController();
            
            boolean res = leasedVehicleController.updateLesaedVehicleWithSearch(searchColumn, searchKey);
        } catch (ClassNotFoundException | SQLException | NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(UpdateLeasedVehicleWithSearchForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void uploadVehiclePhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadVehiclePhotoButtonActionPerformed
        JFileChooser chooser = new JFileChooser("C:\\Users\\Public\\Pictures\\Photos");
        chooser.showOpenDialog(this);
        File file = chooser.getSelectedFile();
        if (file != null) {
            ImageIcon icon = new ImageIcon(new ImageIcon(file.getAbsolutePath()).getImage().getScaledInstance(pictureLabel.getWidth(), pictureLabel.getHeight(), Image.SCALE_SMOOTH));
            pictureLabel.setIcon(icon);
        }
    }//GEN-LAST:event_uploadVehiclePhotoButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            ServerConnector serverConnector = ServerConnector.getServerConnector();
            LeasedVehicleController leasedVehicleController = serverConnector.getLeasedVehicleController();

            searchBy = searchComboBox.getSelectedItem() + "";
            searchColumn = "";
            if (searchBy.equals("Registration No")) {
                searchColumn = "registrationno";
            }
            if (searchBy.equals("Chassis No")) {
                searchColumn = "chassisno";
            }
            if (searchBy.equals("Engine No")) {
                searchColumn = "engineno";
            }

            searchKey = searchTextField.getText();
            
            LeasedVehicle leasedVehicle = leasedVehicleController.searchLeasedVehicleForUpdate(searchColumn, searchKey);
            String chassisNo = leasedVehicle.getChassisNo();
            String colour = leasedVehicle.getColour();
            double cylinderCapacity = leasedVehicle.getCylinderCapacity();
            String engineNo = leasedVehicle.getEngineNo();
            double estimatedPrice = leasedVehicle.getEstimatedPrice();
            double fuelUsed = leasedVehicle.getFuelUsed();
            String licensedDate = leasedVehicle.getLicensedDate();
            int manufacturedYear = leasedVehicle.getManufacturedYear();
            String modelAndName = leasedVehicle.getModelAndName();
            String registrationNo = leasedVehicle.getRegistrationNo();
            String leasingNo = leasedVehicle.getLeasingNo();
            double wheelBase = leasedVehicle.getWheelBase();

            modelNameTextField.setText(modelAndName);
            chassisNoTextField.setText(chassisNo);
            registrationNoTextField.setText(registrationNo);
            engineNoTextField.setText(engineNo);
            manufacturedYearFormattedTextField.setText(manufacturedYear + "");
            estimatedPriceFormattedTextField.setText(estimatedPrice + "");
            colourOfVehicleTextField.setText(colour);
            fuelUseFormattedTextField.setText(fuelUseFormattedTextField + "");
            cylinderCapacityFormattedTextField.setText(cylinderCapacity + "");
            wheelBaseFormattedTextField.setText(wheelBase + "");
            licensedFormattedTextField.setText(licensedDate);

        } catch (NotBoundException | MalformedURLException | RemoteException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UpdateLeasedVehicleWithSearchForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateLeasedVehicleWithSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateLeasedVehicleWithSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateLeasedVehicleWithSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateLeasedVehicleWithSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateLeasedVehicleWithSearchForm dialog = new UpdateLeasedVehicleWithSearchForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EngineNo;
    private javax.swing.JLabel cahssisNoLabel;
    private javax.swing.JTextField chassisNoTextField;
    private javax.swing.JLabel colourOfVehicleLabel;
    private javax.swing.JTextField colourOfVehicleTextField;
    private javax.swing.JFormattedTextField cylinderCapacityFormattedTextField;
    private javax.swing.JLabel cylinderCapacityLabel;
    private javax.swing.JButton deletePhotoButton;
    private javax.swing.JTextField engineNoTextField;
    private javax.swing.JFormattedTextField estimatedPriceFormattedTextField;
    private javax.swing.JLabel estimatedPriceLabel;
    private javax.swing.JFormattedTextField fuelUseFormattedTextField;
    private javax.swing.JLabel fuelUseLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel licensedDateLabel;
    private javax.swing.JFormattedTextField licensedFormattedTextField;
    private javax.swing.JFormattedTextField manufacturedYearFormattedTextField;
    private javax.swing.JLabel manufacturedYearLabel;
    private javax.swing.JLabel modelNameLabel;
    private javax.swing.JTextField modelNameTextField;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JLabel registrationNoLabel;
    private javax.swing.JTextField registrationNoTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchByLabel;
    private javax.swing.JComboBox searchComboBox;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton uploadVehiclePhotoButton;
    private javax.swing.JFormattedTextField wheelBaseFormattedTextField;
    private javax.swing.JLabel wheelBaseLabel;
    // End of variables declaration//GEN-END:variables
}
