/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.leasedVehicle;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Hasitha
 */
public class UpdateLeasedVehicleFrame extends javax.swing.JFrame {

    /**
     * Creates new form UpdateLeasedVehicleFrame
     */
    public UpdateLeasedVehicleFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        registrationNoLabel = new javax.swing.JLabel();
        EngineNo = new javax.swing.JLabel();
        colourOfVehicleLabel = new javax.swing.JLabel();
        cylinderCapacityLabel = new javax.swing.JLabel();
        colourOfVehicleTextField = new javax.swing.JTextField();
        registrationNoTextField = new javax.swing.JTextField();
        engineNoTextField = new javax.swing.JTextField();
        cylinderCapacityFormattedTextField = new javax.swing.JFormattedTextField();
        uploadVehiclePhotoButton = new javax.swing.JButton();
        deletePhotoButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        picturePanel = new javax.swing.JPanel();
        pictureLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrationNoLabel.setText("Registration No :");
        registrationNoLabel.setBounds(20, 290, 100, 14);
        jLayeredPane1.add(registrationNoLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        EngineNo.setText("Engine No :");
        EngineNo.setBounds(20, 320, 100, 14);
        jLayeredPane1.add(EngineNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        colourOfVehicleLabel.setText("Colour Of Vehicle :");
        colourOfVehicleLabel.setBounds(20, 350, 100, 14);
        jLayeredPane1.add(colourOfVehicleLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cylinderCapacityLabel.setText("Cylinder Capacity :");
        cylinderCapacityLabel.setBounds(20, 380, 100, 14);
        jLayeredPane1.add(cylinderCapacityLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        colourOfVehicleTextField.setBounds(130, 350, 140, 20);
        jLayeredPane1.add(colourOfVehicleTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        registrationNoTextField.setBounds(130, 290, 180, 20);
        jLayeredPane1.add(registrationNoTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        engineNoTextField.setBounds(130, 320, 180, 20);
        jLayeredPane1.add(engineNoTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cylinderCapacityFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        cylinderCapacityFormattedTextField.setBounds(130, 380, 109, 20);
        jLayeredPane1.add(cylinderCapacityFormattedTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        uploadVehiclePhotoButton.setText("Upload Vehicle Photo");
        uploadVehiclePhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadVehiclePhotoButtonActionPerformed(evt);
            }
        });
        uploadVehiclePhotoButton.setBounds(300, 90, 190, 23);
        jLayeredPane1.add(uploadVehiclePhotoButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        deletePhotoButton.setText("Delete Photo");
        deletePhotoButton.setBounds(300, 120, 190, 23);
        jLayeredPane1.add(deletePhotoButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        updateButton.setBounds(380, 450, 130, 40);
        jLayeredPane1.add(updateButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pictureLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout picturePanelLayout = new javax.swing.GroupLayout(picturePanel);
        picturePanel.setLayout(picturePanelLayout);
        picturePanelLayout.setHorizontalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
            .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(picturePanelLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );
        picturePanelLayout.setVerticalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
            .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(picturePanelLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        picturePanel.setBounds(20, 40, 190, 190);
        jLayeredPane1.add(picturePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void uploadVehiclePhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadVehiclePhotoButtonActionPerformed
        JFileChooser chooser = new JFileChooser("C:\\Users\\Public\\Pictures\\Photos");
        chooser.showOpenDialog(this);
        File file = chooser.getSelectedFile();
        if (file != null) {
            //try {
                /*BufferedImage bi = ImageIO.read(file);
                BufferedImage dbi = new BufferedImage(bi.getWidth(), bi.getHeight(), BufferedImage.TYPE_INT_RGB);
                Graphics2D g = dbi.createGraphics();
                g.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
                g.drawImage(bi, 0, 0, pictureLabel.getWidth(), pictureLabel.getHeight(), null);
                g.dispose();
                pictureLabel.setIcon(new ImageIcon(dbi));*/
                ImageIcon icon = new ImageIcon(new ImageIcon(file.getAbsolutePath()).getImage().getScaledInstance(pictureLabel.getWidth(), pictureLabel.getHeight(), Image.SCALE_SMOOTH));
                pictureLabel.setIcon(icon);
            //} catch (IOException ex) {
            //    Logger.getLogger(LeasedVehicleForm.class.getName()).log(Level.SEVERE, null, ex);
            //}
        }
    }//GEN-LAST:event_uploadVehiclePhotoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateLeasedVehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateLeasedVehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateLeasedVehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateLeasedVehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateLeasedVehicleFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EngineNo;
    private javax.swing.JLabel colourOfVehicleLabel;
    private javax.swing.JTextField colourOfVehicleTextField;
    private javax.swing.JFormattedTextField cylinderCapacityFormattedTextField;
    private javax.swing.JLabel cylinderCapacityLabel;
    private javax.swing.JButton deletePhotoButton;
    private javax.swing.JTextField engineNoTextField;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JPanel picturePanel;
    private javax.swing.JLabel registrationNoLabel;
    private javax.swing.JTextField registrationNoTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton uploadVehiclePhotoButton;
    // End of variables declaration//GEN-END:variables
}
