/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.leasing;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import lbfinance.serverConnector.ServerConnector;
import lbfinancecommon.controller.LeasedVehicleController;
import lbfinancecommon.controller.LeasingController;
import lbfinancecommon.model.LeasedVehicle;
import lbfinancecommon.model.Leasing;

/**
 *
 * @author Hasitha
 */
public class LeasingForm extends javax.swing.JFrame {

    private static String clientId = null;
    private static File imageFile = null;

    /**
     * Creates new form LeasingForm
     */
    public LeasingForm() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(".\\src\\lbfinance\\images\\TitleLogo.png").getImage());

        backgroundLabel.setSize(this.getSize());
        ImageIcon icon = new ImageIcon(new ImageIcon(".\\src\\lbfinance\\images\\abstract_bg4To3.png").getImage().getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), Image.SCALE_SMOOTH));
        backgroundLabel.setIcon(icon);

        ////////////////////////
        leasingNoTextField.setText("LS000000003");
        clientId = "LS000001";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        leasingDetailsPanel = new javax.swing.JPanel();
        leasingNoLabel = new javax.swing.JLabel();
        noOfPaymentsLabel = new javax.swing.JLabel();
        noOfPaymentsComboBox = new javax.swing.JComboBox();
        totalLeasedCostLabel = new javax.swing.JLabel();
        commenceDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        downPaymentLabel = new javax.swing.JLabel();
        downPaymentFormattedTextField = new javax.swing.JFormattedTextField();
        rentalFeeLabel = new javax.swing.JLabel();
        rentalFeeFormattedTextField = new javax.swing.JFormattedTextField();
        dueDateLabel = new javax.swing.JLabel();
        leasingNoTextField = new javax.swing.JTextField();
        commenceDateChooser = new com.toedter.calendar.JDateChooser();
        dueDayChooser = new com.toedter.components.JSpinField();
        totalLeasedCostFormattedTextField = new javax.swing.JFormattedTextField();
        endDateTextField = new javax.swing.JTextField();
        vehicleDetailsPanel = new javax.swing.JPanel();
        categoryLabel = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox();
        modelNameLabel = new javax.swing.JLabel();
        modelNameTextField = new javax.swing.JTextField();
        chassisNoLabel = new javax.swing.JLabel();
        chassisNoTextField = new javax.swing.JTextField();
        registrationNoLabel = new javax.swing.JLabel();
        registrationNoTextField = new javax.swing.JTextField();
        engineNoLabel = new javax.swing.JLabel();
        engineNoTextField = new javax.swing.JTextField();
        mfdYearLabel = new javax.swing.JLabel();
        mfdYearFormattedTextField = new javax.swing.JFormattedTextField();
        estimatedPriceLabel = new javax.swing.JLabel();
        estimatedPriceFormattedTextField = new javax.swing.JFormattedTextField();
        colourLabel = new javax.swing.JLabel();
        colourTextField = new javax.swing.JTextField();
        fuelUsedLabel = new javax.swing.JLabel();
        fuelUsedFormattedTextField = new javax.swing.JFormattedTextField();
        cylinderCapacityLabel = new javax.swing.JLabel();
        cylinderCapacityFormattedTextField = new javax.swing.JFormattedTextField();
        wheelBaseLabel = new javax.swing.JLabel();
        wheelBaseFormattedTextField = new javax.swing.JFormattedTextField();
        licensedLabel = new javax.swing.JLabel();
        deletePictureButton = new javax.swing.JButton();
        uploadPictureButton = new javax.swing.JButton();
        pictureLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        licensedDateChooser = new com.toedter.calendar.JDateChooser();
        submitButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leasingDetailsPanel.setBackground(new java.awt.Color(0, 0, 0));
        leasingDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Leasing Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        leasingDetailsPanel.setOpaque(false);

        leasingNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leasingNoLabel.setText("Leasing No :");

        noOfPaymentsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noOfPaymentsLabel.setText("No. of Payments :");

        noOfPaymentsComboBox.setBackground(new java.awt.Color(204, 204, 204));
        noOfPaymentsComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noOfPaymentsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "24", "36", "48", "60" }));
        noOfPaymentsComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noOfPaymentsComboBoxMouseClicked(evt);
            }
        });
        noOfPaymentsComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                noOfPaymentsComboBoxKeyReleased(evt);
            }
        });

        totalLeasedCostLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalLeasedCostLabel.setText("Total leased cost :");

        commenceDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        commenceDateLabel.setText("Commence Date :");

        endDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endDateLabel.setText("End Date :");

        downPaymentLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        downPaymentLabel.setText("Down Payment :");

        downPaymentFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        downPaymentFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        downPaymentFormattedTextField.setEnabled(false);
        downPaymentFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        downPaymentFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downPaymentFormattedTextFieldActionPerformed(evt);
            }
        });

        rentalFeeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rentalFeeLabel.setText("Rental Fee :");

        rentalFeeFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        rentalFeeFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        rentalFeeFormattedTextField.setEnabled(false);
        rentalFeeFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rentalFeeFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalFeeFormattedTextFieldActionPerformed(evt);
            }
        });

        dueDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dueDateLabel.setText("Due Date :");

        leasingNoTextField.setBackground(new java.awt.Color(233, 231, 231));
        leasingNoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leasingNoTextField.setEnabled(false);

        commenceDateChooser.setBackground(new java.awt.Color(233, 231, 231));
        commenceDateChooser.setDateFormatString("yyyy-MM-dd");
        commenceDateChooser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dueDayChooser.setBackground(new java.awt.Color(204, 204, 204));
        dueDayChooser.setEnabled(false);
        dueDayChooser.setMaximum(31);
        dueDayChooser.setMinimum(0);
        dueDayChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dueDayChooserKeyReleased(evt);
            }
        });

        totalLeasedCostFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        totalLeasedCostFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        totalLeasedCostFormattedTextField.setEnabled(false);
        totalLeasedCostFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalLeasedCostFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalLeasedCostFormattedTextFieldActionPerformed(evt);
            }
        });

        endDateTextField.setBackground(new java.awt.Color(233, 231, 231));
        endDateTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endDateTextField.setEnabled(false);

        javax.swing.GroupLayout leasingDetailsPanelLayout = new javax.swing.GroupLayout(leasingDetailsPanel);
        leasingDetailsPanel.setLayout(leasingDetailsPanelLayout);
        leasingDetailsPanelLayout.setHorizontalGroup(
            leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leasingDetailsPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leasingDetailsPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(downPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(noOfPaymentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalLeasedCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(commenceDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(leasingNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addComponent(endDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rentalFeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dueDayChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentalFeeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downPaymentFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLeasedCostFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noOfPaymentsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commenceDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leasingNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        leasingDetailsPanelLayout.setVerticalGroup(
            leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leasingDetailsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leasingNoLabel)
                    .addComponent(leasingNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(commenceDateLabel)
                    .addComponent(commenceDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfPaymentsLabel)
                    .addComponent(noOfPaymentsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDateLabel)
                    .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downPaymentLabel)
                    .addComponent(downPaymentFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLeasedCostLabel)
                    .addComponent(totalLeasedCostFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentalFeeLabel)
                    .addComponent(rentalFeeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leasingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dueDateLabel)
                    .addComponent(dueDayChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLayeredPane1.add(leasingDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 380));

        vehicleDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Vehicle Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        vehicleDetailsPanel.setOpaque(false);

        categoryLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoryLabel.setText("Vehicle Category:");

        categoryComboBox.setBackground(new java.awt.Color(204, 204, 204));
        categoryComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A1", "B", "B1", " " }));
        categoryComboBox.setEnabled(false);
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        modelNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modelNameLabel.setText("Model & Name :");

        modelNameTextField.setBackground(new java.awt.Color(233, 231, 231));
        modelNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modelNameTextField.setEnabled(false);
        modelNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNameTextFieldActionPerformed(evt);
            }
        });

        chassisNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chassisNoLabel.setText("Chassis No :");

        chassisNoTextField.setBackground(new java.awt.Color(233, 231, 231));
        chassisNoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chassisNoTextField.setEnabled(false);
        chassisNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chassisNoTextFieldActionPerformed(evt);
            }
        });

        registrationNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registrationNoLabel.setText("Registration No :");

        registrationNoTextField.setBackground(new java.awt.Color(233, 231, 231));
        registrationNoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registrationNoTextField.setEnabled(false);
        registrationNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationNoTextFieldActionPerformed(evt);
            }
        });

        engineNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        engineNoLabel.setText("Engine No :");

        engineNoTextField.setBackground(new java.awt.Color(233, 231, 231));
        engineNoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        engineNoTextField.setEnabled(false);
        engineNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineNoTextFieldActionPerformed(evt);
            }
        });

        mfdYearLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mfdYearLabel.setText("Manufactured Year :");

        mfdYearFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        mfdYearFormattedTextField.setEnabled(false);
        mfdYearFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mfdYearFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfdYearFormattedTextFieldActionPerformed(evt);
            }
        });

        estimatedPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estimatedPriceLabel.setText("Estimated Price :");

        estimatedPriceFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        estimatedPriceFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        estimatedPriceFormattedTextField.setEnabled(false);
        estimatedPriceFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estimatedPriceFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimatedPriceFormattedTextFieldActionPerformed(evt);
            }
        });

        colourLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colourLabel.setText("Colour Of Vehicle :");

        colourTextField.setBackground(new java.awt.Color(233, 231, 231));
        colourTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colourTextField.setEnabled(false);
        colourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourTextFieldActionPerformed(evt);
            }
        });

        fuelUsedLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fuelUsedLabel.setText("Fuel Used :");

        fuelUsedFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        fuelUsedFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        fuelUsedFormattedTextField.setEnabled(false);
        fuelUsedFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fuelUsedFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelUsedFormattedTextFieldActionPerformed(evt);
            }
        });

        cylinderCapacityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cylinderCapacityLabel.setText("Cylinder Capacity :");

        cylinderCapacityFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        cylinderCapacityFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        cylinderCapacityFormattedTextField.setEnabled(false);
        cylinderCapacityFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cylinderCapacityFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cylinderCapacityFormattedTextFieldActionPerformed(evt);
            }
        });

        wheelBaseLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wheelBaseLabel.setText("Wheel Base :");

        wheelBaseFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        wheelBaseFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        wheelBaseFormattedTextField.setEnabled(false);
        wheelBaseFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wheelBaseFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheelBaseFormattedTextFieldActionPerformed(evt);
            }
        });

        licensedLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        licensedLabel.setText("Licensed Date :");

        deletePictureButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deletePictureButton.setText("Delete Photo");
        deletePictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePictureButtonActionPerformed(evt);
            }
        });

        uploadPictureButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uploadPictureButton.setText("Upload Vehicle Photo");
        uploadPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPictureButtonActionPerformed(evt);
            }
        });

        pictureLabel.setBackground(new java.awt.Color(231, 231, 231));
        pictureLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        pictureLabel.setOpaque(true);

        jLabel1.setText("(kilometres per litre)");

        jLabel2.setText("CC");

        jLabel3.setText("in.");

        licensedDateChooser.setBackground(new java.awt.Color(231, 231, 231));
        licensedDateChooser.setDateFormatString("yyyy-MM-dd");
        licensedDateChooser.setEnabled(false);
        licensedDateChooser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout vehicleDetailsPanelLayout = new javax.swing.GroupLayout(vehicleDetailsPanel);
        vehicleDetailsPanel.setLayout(vehicleDetailsPanelLayout);
        vehicleDetailsPanelLayout.setHorizontalGroup(
            vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wheelBaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licensedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engineNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelUsedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chassisNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cylinderCapacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrationNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mfdYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estimatedPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                        .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                                    .addComponent(wheelBaseFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3))
                                .addComponent(mfdYearFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(modelNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(registrationNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(estimatedPriceFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(engineNoTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chassisNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                                    .addComponent(cylinderCapacityFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)))
                            .addComponent(colourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deletePictureButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uploadPictureButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pictureLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                        .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                                .addComponent(fuelUsedFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(licensedDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        vehicleDetailsPanelLayout.setVerticalGroup(
            vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(categoryLabel)
                                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(modelNameLabel)
                                    .addComponent(modelNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mfdYearLabel)
                                    .addComponent(mfdYearFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(registrationNoLabel)
                                    .addComponent(registrationNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(estimatedPriceLabel)
                                    .addComponent(estimatedPriceFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chassisNoLabel)
                                    .addComponent(chassisNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(engineNoLabel)
                                    .addComponent(engineNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(colourLabel)
                                    .addComponent(colourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fuelUsedLabel)
                                    .addComponent(fuelUsedFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cylinderCapacityLabel)
                                    .addComponent(cylinderCapacityFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(wheelBaseLabel)
                                    .addComponent(wheelBaseFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(vehicleDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(licensedLabel)
                                    .addComponent(licensedDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(uploadPictureButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletePictureButton))))
                    .addGroup(vehicleDetailsPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(vehicleDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 690, 440));

        submitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 510, -1, -1));
        jLayeredPane1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 550));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletePictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePictureButtonActionPerformed
        pictureLabel.setIcon(null);
    }//GEN-LAST:event_deletePictureButtonActionPerformed

    private void uploadPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPictureButtonActionPerformed
        JFileChooser chooser = new JFileChooser("C:\\Users\\Public\\Pictures\\Photos");
        chooser.showOpenDialog(this);
        imageFile = chooser.getSelectedFile();
        if (imageFile != null) {
            ImageIcon icon = new ImageIcon(new ImageIcon(imageFile.getAbsolutePath()).getImage().getScaledInstance(pictureLabel.getWidth(), pictureLabel.getHeight(), Image.SCALE_SMOOTH));
            pictureLabel.setIcon(icon);
        }
    }//GEN-LAST:event_uploadPictureButtonActionPerformed

    private void noOfPaymentsComboBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noOfPaymentsComboBoxKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && commenceDateChooser.getDate() != null) {
            Date comenceDate = commenceDateChooser.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String commenceDateString = dateFormat.format(comenceDate);
            String endDate = null;
            if (noOfPaymentsComboBox.getSelectedItem() == "12") {
                int newYear = Integer.parseInt(commenceDateString.substring(0, 4)) + 1;
                String monthAndDay = commenceDateString.substring(4, commenceDateString.length());
                endDate = newYear + monthAndDay;
            } else if (noOfPaymentsComboBox.getSelectedItem() == "24") {
                int newYear = Integer.parseInt(commenceDateString.substring(0, 4)) + 2;
                String monthAndDay = commenceDateString.substring(4, commenceDateString.length());
                endDate = newYear + monthAndDay;
            } else if (noOfPaymentsComboBox.getSelectedItem() == "36") {
                int newYear = Integer.parseInt(commenceDateString.substring(0, 4)) + 3;
                String monthAndDay = commenceDateString.substring(4, commenceDateString.length());
                endDate = newYear + monthAndDay;
            } else if (noOfPaymentsComboBox.getSelectedItem() == "48") {
                int newYear = Integer.parseInt(commenceDateString.substring(0, 4)) + 4;
                String monthAndDay = commenceDateString.substring(4, commenceDateString.length());
                endDate = newYear + monthAndDay;
            } else if (noOfPaymentsComboBox.getSelectedItem() == "60") {
                int newYear = Integer.parseInt(commenceDateString.substring(0, 4)) + 5;
                String monthAndDay = commenceDateString.substring(4, commenceDateString.length());
                endDate = newYear + monthAndDay;
            }
            endDateTextField.setText(endDate);
            downPaymentFormattedTextField.setEnabled(true);
            downPaymentFormattedTextField.requestFocus();
        } else {

        }
    }//GEN-LAST:event_noOfPaymentsComboBoxKeyReleased

    private void downPaymentFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downPaymentFormattedTextFieldActionPerformed
        if (downPaymentFormattedTextField.getText() != null) {
            totalLeasedCostFormattedTextField.setEnabled(true);
            totalLeasedCostFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_downPaymentFormattedTextFieldActionPerformed

    private void totalLeasedCostFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalLeasedCostFormattedTextFieldActionPerformed
        if (totalLeasedCostFormattedTextField.getText() != null) {
            rentalFeeFormattedTextField.setEnabled(true);
            rentalFeeFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_totalLeasedCostFormattedTextFieldActionPerformed

    private void rentalFeeFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalFeeFormattedTextFieldActionPerformed
        if (rentalFeeFormattedTextField.getText() != null) {
            dueDayChooser.setEnabled(true);
            dueDayChooser.requestFocus();
        }
    }//GEN-LAST:event_rentalFeeFormattedTextFieldActionPerformed

    private void dueDayChooserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dueDayChooserKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && dueDayChooser.getValue() != 0) {
            categoryComboBox.setEnabled(true);
            categoryComboBox.requestFocus();
            categoryComboBox.showPopup();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            dueDayChooser.setValue(dueDayChooser.getValue() + 1);
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN && dueDayChooser.getValue() != 0) {
            dueDayChooser.setValue(dueDayChooser.getValue() - 1);
        }
    }//GEN-LAST:event_dueDayChooserKeyReleased

    private void noOfPaymentsComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noOfPaymentsComboBoxMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            Date comenceDate = commenceDateChooser.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String commenceDateString = dateFormat.format(comenceDate);
            System.out.println(commenceDateString);
            String endDate = null;
            if (noOfPaymentsComboBox.getSelectedItem() == "12") {
                int newYear = Integer.parseInt(commenceDateString.substring(0, 4)) + 1;
                String monthAndDay = commenceDateString.substring(4, commenceDateString.length());
                endDate = newYear + monthAndDay;
            } else if (noOfPaymentsComboBox.getSelectedItem() == "24") {
                int newYear = Integer.parseInt(commenceDateString.substring(0, 4)) + 2;
                String monthAndDay = commenceDateString.substring(4, commenceDateString.length());
                endDate = newYear + monthAndDay;
            } else if (noOfPaymentsComboBox.getSelectedItem() == "36") {
                int newYear = Integer.parseInt(commenceDateString.substring(0, 4)) + 3;
                String monthAndDay = commenceDateString.substring(4, commenceDateString.length());
                endDate = newYear + monthAndDay;
            } else if (noOfPaymentsComboBox.getSelectedItem() == "48") {
                int newYear = Integer.parseInt(commenceDateString.substring(0, 4)) + 4;
                String monthAndDay = commenceDateString.substring(4, commenceDateString.length());
                endDate = newYear + monthAndDay;
            } else if (noOfPaymentsComboBox.getSelectedItem() == "60") {
                int newYear = Integer.parseInt(commenceDateString.substring(0, 4)) + 5;
                String monthAndDay = commenceDateString.substring(4, commenceDateString.length());
                endDate = newYear + monthAndDay;
            }
            endDateTextField.setText(endDate);
            downPaymentFormattedTextField.setEnabled(true);
            downPaymentFormattedTextField.requestFocus();
        } else {

        }
    }//GEN-LAST:event_noOfPaymentsComboBoxMouseClicked

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        modelNameTextField.setEnabled(true);
        modelNameTextField.requestFocus();
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void modelNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNameTextFieldActionPerformed
        if (modelNameTextField.getText() != null) {
            mfdYearFormattedTextField.setEnabled(true);
            mfdYearFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_modelNameTextFieldActionPerformed

    private void mfdYearFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfdYearFormattedTextFieldActionPerformed
        if (mfdYearFormattedTextField.getText() != null) {
            registrationNoTextField.setEnabled(true);
            registrationNoTextField.requestFocus();
        }
    }//GEN-LAST:event_mfdYearFormattedTextFieldActionPerformed

    private void registrationNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationNoTextFieldActionPerformed
        if (registrationNoTextField.getText() != null) {
            estimatedPriceFormattedTextField.setEnabled(true);
            estimatedPriceFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_registrationNoTextFieldActionPerformed

    private void estimatedPriceFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimatedPriceFormattedTextFieldActionPerformed
        if (estimatedPriceFormattedTextField.getText() != null) {
            chassisNoTextField.setEnabled(true);
            chassisNoTextField.requestFocus();
        }
    }//GEN-LAST:event_estimatedPriceFormattedTextFieldActionPerformed

    private void chassisNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chassisNoTextFieldActionPerformed
        if (chassisNoTextField.getText() != null) {
            engineNoTextField.setEnabled(true);
            engineNoTextField.requestFocus();
        }
    }//GEN-LAST:event_chassisNoTextFieldActionPerformed

    private void engineNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineNoTextFieldActionPerformed
        if (engineNoTextField.getText() != null) {
            colourTextField.setEnabled(true);
            colourTextField.requestFocus();
        }
    }//GEN-LAST:event_engineNoTextFieldActionPerformed

    private void colourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourTextFieldActionPerformed
        if (colourTextField.getText() != null) {
            fuelUsedFormattedTextField.setEnabled(true);
            fuelUsedFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_colourTextFieldActionPerformed

    private void fuelUsedFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelUsedFormattedTextFieldActionPerformed
        String text = fuelUsedFormattedTextField.getText();
        double textD =Double.parseDouble(text);
        String textString = Double.toString(textD);
        fuelUsedFormattedTextField.setText(textString);
        if (fuelUsedFormattedTextField.getText() != null) {
            cylinderCapacityFormattedTextField.setEnabled(true);
            cylinderCapacityFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_fuelUsedFormattedTextFieldActionPerformed

    private void cylinderCapacityFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cylinderCapacityFormattedTextFieldActionPerformed
        String text = fuelUsedFormattedTextField.getText();
        double textD =Double.parseDouble(text);
        String textString = Double.toString(textD);
        cylinderCapacityFormattedTextField.setText(textString);
        if (cylinderCapacityFormattedTextField.getText() != null) {
            wheelBaseFormattedTextField.setEnabled(true);
            wheelBaseFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_cylinderCapacityFormattedTextFieldActionPerformed

    private void wheelBaseFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheelBaseFormattedTextFieldActionPerformed
        String text = fuelUsedFormattedTextField.getText();
        double textD =Double.parseDouble(text);
        String textString = Double.toString(textD);
        wheelBaseFormattedTextField.setText(textString);
        if (wheelBaseFormattedTextField.getText() != null) {
            licensedDateChooser.setEnabled(true);
            licensedDateChooser.requestFocus();
        }
    }//GEN-LAST:event_wheelBaseFormattedTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            //get leasing details
            String leasingNo = leasingNoTextField.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date commence = commenceDateChooser.getDate();
            String commenceDate = dateFormat.format(commence);
            String noOfPaymentString = (String) noOfPaymentsComboBox.getSelectedItem();
            int noOfPayment = Integer.parseInt(noOfPaymentString);
            String endDate = endDateTextField.getText();
            double downPayment = Double.parseDouble(downPaymentFormattedTextField.getText());
            double totalLeasedCost = Double.parseDouble(totalLeasedCostFormattedTextField.getText());
            double rentalFee = Double.parseDouble(rentalFeeFormattedTextField.getText());
            String dueDate = Integer.toString(dueDayChooser.getValue());
            
            Leasing leasing = new Leasing(leasingNo, clientId, noOfPayment, totalLeasedCost, commenceDate, endDate, downPayment, rentalFee, dueDate);
            
            //get leasedVehicle Details
            String vehicleCategory = (String) categoryComboBox.getSelectedItem();
            String modelName = modelNameTextField.getText();
            int mfdYear = Integer.parseInt(mfdYearFormattedTextField.getText());
            String registrationNo = registrationNoTextField.getText();
            double estimatedPrice = Double.parseDouble(estimatedPriceFormattedTextField.getText());
            String chassisNo = chassisNoTextField.getText();
            String engineNo = engineNoTextField.getText();
            String color = colourTextField.getText();
            double fuelUsed = Double.parseDouble(fuelUsedFormattedTextField.getText());
            double cylinderCapacity = Double.parseDouble(cylinderCapacityFormattedTextField.getText());
            double wheelBase = Double.parseDouble(wheelBaseFormattedTextField.getText());
            Date licensed = licensedDateChooser.getDate();
            String licensedDate = dateFormat.format(licensed);
            
            LeasedVehicle leasedVehicle = new LeasedVehicle(leasingNo, vehicleCategory, modelName, chassisNo, registrationNo, engineNo, mfdYear, estimatedPrice, color, fuelUsed, cylinderCapacity, wheelBase, licensedDate, imageFile);
            
            //upload
            ServerConnector serverConnector = ServerConnector.getServerConnector();
            LeasingController leasingController =serverConnector.getLeasingController();
            LeasedVehicleController leasedVehicleController = serverConnector.getLeasedVehicleController();
            
            boolean res1 = leasingController.addNewLeasingDetails(leasing);
            if(res1){
                boolean res2 = leasedVehicleController.addLeasedVehicle(leasedVehicle);
                if(res2){
                    JOptionPane.showMessageDialog(this, "Leasing details added successfully.", "Message", JOptionPane.PLAIN_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add details.", "Message", JOptionPane.PLAIN_MESSAGE);
                    boolean res3 = leasingController.removeLeasingDetails(leasing);
                }
            }
            
        } catch (NotBoundException | MalformedURLException | RemoteException | ClassNotFoundException | NumberFormatException | SQLException | FileNotFoundException ex) {
            Logger.getLogger(LeasingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    public static void setClientId(String clientID){
        clientId =clientID;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeasingForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeasingForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeasingForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeasingForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeasingForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel chassisNoLabel;
    private javax.swing.JTextField chassisNoTextField;
    private javax.swing.JLabel colourLabel;
    private javax.swing.JTextField colourTextField;
    private com.toedter.calendar.JDateChooser commenceDateChooser;
    private javax.swing.JLabel commenceDateLabel;
    private javax.swing.JFormattedTextField cylinderCapacityFormattedTextField;
    private javax.swing.JLabel cylinderCapacityLabel;
    private javax.swing.JButton deletePictureButton;
    private javax.swing.JFormattedTextField downPaymentFormattedTextField;
    private javax.swing.JLabel downPaymentLabel;
    private javax.swing.JLabel dueDateLabel;
    private com.toedter.components.JSpinField dueDayChooser;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JLabel engineNoLabel;
    private javax.swing.JTextField engineNoTextField;
    private javax.swing.JFormattedTextField estimatedPriceFormattedTextField;
    private javax.swing.JLabel estimatedPriceLabel;
    private javax.swing.JFormattedTextField fuelUsedFormattedTextField;
    private javax.swing.JLabel fuelUsedLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel leasingDetailsPanel;
    private javax.swing.JLabel leasingNoLabel;
    private javax.swing.JTextField leasingNoTextField;
    private com.toedter.calendar.JDateChooser licensedDateChooser;
    private javax.swing.JLabel licensedLabel;
    private javax.swing.JFormattedTextField mfdYearFormattedTextField;
    private javax.swing.JLabel mfdYearLabel;
    private javax.swing.JLabel modelNameLabel;
    private javax.swing.JTextField modelNameTextField;
    private javax.swing.JComboBox noOfPaymentsComboBox;
    private javax.swing.JLabel noOfPaymentsLabel;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JLabel registrationNoLabel;
    private javax.swing.JTextField registrationNoTextField;
    private javax.swing.JFormattedTextField rentalFeeFormattedTextField;
    private javax.swing.JLabel rentalFeeLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JFormattedTextField totalLeasedCostFormattedTextField;
    private javax.swing.JLabel totalLeasedCostLabel;
    private javax.swing.JButton uploadPictureButton;
    private javax.swing.JPanel vehicleDetailsPanel;
    private javax.swing.JFormattedTextField wheelBaseFormattedTextField;
    private javax.swing.JLabel wheelBaseLabel;
    // End of variables declaration//GEN-END:variables
}
