/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.guarantor;

import java.awt.Color;
import java.awt.Image;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lbfinance.serverConnector.ServerConnector;
import lbfinance.important.Validation;
import lbfinancecommon.controller.GuarentorBankersController;
import lbfinancecommon.controller.GuarentorController;
import lbfinancecommon.controller.GuarentorIncomeTaxController;
import lbfinancecommon.model.Guarentor;
import lbfinancecommon.model.GuarentorBankers;
import lbfinancecommon.model.GuarentorIncomeTax;

/**
 *
 * @author Hasitha
 */
public class AddFirstGuarantorForm extends javax.swing.JFrame {

    private static String leasingNo;
    private String statusInPvt;
    private String maritalStatus;
    private String organizationType;
    private int currentYear;

    /**
     * Creates new form AddFirstGuarantorForm
     */
    public AddFirstGuarantorForm() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(".\\src\\lbfinance\\images\\TitleLogo.png").getImage());
        //setSize(Toolkit.getDefaultToolkit().getScreenSize());

        ///////////////////////////////
        leasingNo = "LS00000001";
        guarantorIdTextField.setText("GU00001");
        
        ButtonGroup statusInPvtBG =new ButtonGroup();
        statusInPvtBG.add(ownerRadioButton);
        statusInPvtBG.add(tenantRadioButton);
        statusInPvtBG.add(boarderRadioButton);
        
        ButtonGroup organizationTypeBG = new ButtonGroup();
        organizationTypeBG.add(soleProprietorshipRadioButton);
        organizationTypeBG.add(partnershipRadioButton);
        organizationTypeBG.add(limitedComanyRadioButton);
        
        ButtonGroup maritalStatusBG = new ButtonGroup();
        maritalStatusBG.add(marriedRadioButton);
        maritalStatusBG.add(unmarriedRadioButton);
        
        Calendar c = Calendar.getInstance();
        currentYear = c.getWeekYear();

        yearComboBox.addItem(currentYear - 3);
        yearComboBox.addItem(currentYear - 2);
        yearComboBox.addItem(currentYear - 1);
        taxableIncomeFormattedTextField.setEnabled(false);

        nameTextField.requestFocus();
        
        backgroundLabel.setSize(this.getSize());
        ImageIcon icon = new ImageIcon(new ImageIcon(".\\src\\lbfinance\\images\\abstract_bg4To3.png").getImage().getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), Image.SCALE_SMOOTH));
        backgroundLabel.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        recognitionDetailPanel = new javax.swing.JPanel();
        guarantorIdLabel = new javax.swing.JLabel();
        guarantorIdTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        nicLabel = new javax.swing.JLabel();
        citizenshipLabel = new javax.swing.JLabel();
        citizenshipTextField = new javax.swing.JTextField();
        nicFormattedTextField = new javax.swing.JFormattedTextField();
        contactDeatailPanel = new javax.swing.JPanel();
        pvtAddressLabel = new javax.swing.JLabel();
        privateAddressTextField = new javax.swing.JTextField();
        officialAddressLabel = new javax.swing.JLabel();
        officialAddressTextField = new javax.swing.JTextField();
        statusPvtLabel = new javax.swing.JLabel();
        telNoLabel = new javax.swing.JLabel();
        ownerRadioButton = new javax.swing.JRadioButton();
        tenantRadioButton = new javax.swing.JRadioButton();
        boarderRadioButton = new javax.swing.JRadioButton();
        telNoFormattedTextField = new javax.swing.JFormattedTextField();
        otherDetailPanel = new javax.swing.JPanel();
        occupationLabel = new javax.swing.JLabel();
        occupationTextField = new javax.swing.JTextField();
        organizationTypeLabel = new javax.swing.JLabel();
        soleProprietorshipRadioButton = new javax.swing.JRadioButton();
        partnershipRadioButton = new javax.swing.JRadioButton();
        limitedComanyRadioButton = new javax.swing.JRadioButton();
        residentDurationLabel = new javax.swing.JLabel();
        maritalLabel = new javax.swing.JLabel();
        marriedRadioButton = new javax.swing.JRadioButton();
        unmarriedRadioButton = new javax.swing.JRadioButton();
        incomeSourceLabel = new javax.swing.JLabel();
        incomeSourceTextField = new javax.swing.JTextField();
        monthlyIncomeLabel = new javax.swing.JLabel();
        monthlyIncomeFormattedTextField = new javax.swing.JFormattedTextField();
        residentDurationYearLabel = new javax.swing.JLabel();
        residentDurationMonthsLabel = new javax.swing.JLabel();
        residentDurationDaysLabel = new javax.swing.JLabel();
        residentDurationYearFormattedTextField = new javax.swing.JFormattedTextField();
        residentDurationMonthsFormattedTextField = new javax.swing.JFormattedTextField();
        residentDurationDaysFormattedTextField = new javax.swing.JFormattedTextField();
        submitButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        incomeTaxPanel = new javax.swing.JPanel();
        yearLabel = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox();
        taxableIncomeLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taxTable = new javax.swing.JTable();
        taxableIncomeFormattedTextField = new javax.swing.JFormattedTextField();
        taxFormattedTextField = new javax.swing.JFormattedTextField();
        bankersPanel = new javax.swing.JPanel();
        bankNameLabel = new javax.swing.JLabel();
        bankAddressLabel = new javax.swing.JLabel();
        accountNoLabel = new javax.swing.JLabel();
        bankNameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        accNoTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bankTable = new javax.swing.JTable();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recognitionDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Recognition Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        recognitionDetailPanel.setOpaque(false);
        recognitionDetailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guarantorIdLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guarantorIdLabel.setText("Guarantor ID :");
        recognitionDetailPanel.add(guarantorIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 32, -1, -1));

        guarantorIdTextField.setEditable(false);
        guarantorIdTextField.setBackground(new java.awt.Color(233, 231, 231));
        guarantorIdTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recognitionDetailPanel.add(guarantorIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 30, 99, 21));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel.setText("Guarantor Name:");
        recognitionDetailPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, -1, -1));

        nameTextField.setBackground(new java.awt.Color(233, 231, 231));
        nameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyReleased(evt);
            }
        });
        recognitionDetailPanel.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 60, 354, 21));

        nicLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nicLabel.setText("NIC No :");
        recognitionDetailPanel.add(nicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 87, -1, -1));

        citizenshipLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        citizenshipLabel.setText("Citizenship :");
        recognitionDetailPanel.add(citizenshipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, -1, -1));

        citizenshipTextField.setBackground(new java.awt.Color(233, 231, 231));
        citizenshipTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        citizenshipTextField.setEnabled(false);
        citizenshipTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizenshipTextFieldActionPerformed(evt);
            }
        });
        citizenshipTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                citizenshipTextFieldKeyReleased(evt);
            }
        });
        recognitionDetailPanel.add(citizenshipTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 116, 170, 21));

        nicFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        try {
            nicFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########v")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nicFormattedTextField.setEnabled(false);
        nicFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nicFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicFormattedTextFieldActionPerformed(evt);
            }
        });
        recognitionDetailPanel.add(nicFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 87, 170, -1));

        jLayeredPane1.add(recognitionDetailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 590, 150));

        contactDeatailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Contact Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        contactDeatailPanel.setOpaque(false);
        contactDeatailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pvtAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pvtAddressLabel.setText("Private Address :");
        contactDeatailPanel.add(pvtAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 35, -1, -1));

        privateAddressTextField.setBackground(new java.awt.Color(233, 231, 231));
        privateAddressTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        privateAddressTextField.setEnabled(false);
        privateAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privateAddressTextFieldActionPerformed(evt);
            }
        });
        contactDeatailPanel.add(privateAddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 33, 385, 21));

        officialAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        officialAddressLabel.setText("Official Address :");
        contactDeatailPanel.add(officialAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 62, -1, -1));

        officialAddressTextField.setBackground(new java.awt.Color(233, 231, 231));
        officialAddressTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        officialAddressTextField.setEnabled(false);
        officialAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officialAddressTextFieldActionPerformed(evt);
            }
        });
        contactDeatailPanel.add(officialAddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 385, 21));

        statusPvtLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusPvtLabel.setText("Status in Private Address :");
        contactDeatailPanel.add(statusPvtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 87, -1, -1));

        telNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telNoLabel.setText("Tel. No :");
        contactDeatailPanel.add(telNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 113, -1, -1));

        ownerRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ownerRadioButton.setText("Owner");
        ownerRadioButton.setOpaque(false);
        ownerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerRadioButtonActionPerformed(evt);
            }
        });
        contactDeatailPanel.add(ownerRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 83, -1, -1));

        tenantRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenantRadioButton.setText("Tenant");
        tenantRadioButton.setOpaque(false);
        tenantRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantRadioButtonActionPerformed(evt);
            }
        });
        contactDeatailPanel.add(tenantRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 83, -1, -1));

        boarderRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boarderRadioButton.setText("Boarder");
        boarderRadioButton.setOpaque(false);
        boarderRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boarderRadioButtonActionPerformed(evt);
            }
        });
        contactDeatailPanel.add(boarderRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 83, -1, -1));

        telNoFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        try {
            telNoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0##-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telNoFormattedTextField.setEnabled(false);
        telNoFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telNoFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telNoFormattedTextFieldActionPerformed(evt);
            }
        });
        contactDeatailPanel.add(telNoFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 136, -1));

        jLayeredPane1.add(contactDeatailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 590, 150));

        otherDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Other Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        otherDetailPanel.setOpaque(false);
        otherDetailPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        occupationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        occupationLabel.setText("Occupation :");
        otherDetailPanel.add(occupationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 23, -1, -1));

        occupationTextField.setBackground(new java.awt.Color(233, 231, 231));
        occupationTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        occupationTextField.setEnabled(false);
        occupationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationTextFieldActionPerformed(evt);
            }
        });
        occupationTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                occupationTextFieldKeyReleased(evt);
            }
        });
        otherDetailPanel.add(occupationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 21, 354, 21));

        organizationTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        organizationTypeLabel.setText("Organization Type :");
        otherDetailPanel.add(organizationTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 48, -1, -1));

        soleProprietorshipRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        soleProprietorshipRadioButton.setText("Sole Proprietorship");
        soleProprietorshipRadioButton.setOpaque(false);
        soleProprietorshipRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soleProprietorshipRadioButtonActionPerformed(evt);
            }
        });
        otherDetailPanel.add(soleProprietorshipRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 48, -1, -1));

        partnershipRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        partnershipRadioButton.setText("Partnership");
        partnershipRadioButton.setOpaque(false);
        partnershipRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partnershipRadioButtonActionPerformed(evt);
            }
        });
        otherDetailPanel.add(partnershipRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 48, -1, -1));

        limitedComanyRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        limitedComanyRadioButton.setText("Limited Company");
        limitedComanyRadioButton.setOpaque(false);
        limitedComanyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitedComanyRadioButtonActionPerformed(evt);
            }
        });
        otherDetailPanel.add(limitedComanyRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 48, -1, -1));

        residentDurationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        residentDurationLabel.setText("Resident Duration :");
        otherDetailPanel.add(residentDurationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 80, -1, -1));

        maritalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maritalLabel.setText("Marital Status :");
        otherDetailPanel.add(maritalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 114, -1, -1));

        marriedRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        marriedRadioButton.setText("Married");
        marriedRadioButton.setOpaque(false);
        marriedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marriedRadioButtonActionPerformed(evt);
            }
        });
        otherDetailPanel.add(marriedRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 110, -1, -1));

        unmarriedRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unmarriedRadioButton.setText("Unmarried");
        unmarriedRadioButton.setOpaque(false);
        unmarriedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unmarriedRadioButtonActionPerformed(evt);
            }
        });
        otherDetailPanel.add(unmarriedRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 110, -1, -1));

        incomeSourceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        incomeSourceLabel.setText("Income Source :");
        otherDetailPanel.add(incomeSourceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 139, -1, -1));

        incomeSourceTextField.setBackground(new java.awt.Color(233, 231, 231));
        incomeSourceTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        incomeSourceTextField.setEnabled(false);
        incomeSourceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeSourceTextFieldActionPerformed(evt);
            }
        });
        incomeSourceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                incomeSourceTextFieldKeyReleased(evt);
            }
        });
        otherDetailPanel.add(incomeSourceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 137, 354, 21));

        monthlyIncomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        monthlyIncomeLabel.setText("Totally Monthly Income :");
        otherDetailPanel.add(monthlyIncomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 167, -1, -1));

        monthlyIncomeFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        monthlyIncomeFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        monthlyIncomeFormattedTextField.setEnabled(false);
        monthlyIncomeFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        monthlyIncomeFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyIncomeFormattedTextFieldActionPerformed(evt);
            }
        });
        otherDetailPanel.add(monthlyIncomeFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 164, 120, -1));

        residentDurationYearLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        residentDurationYearLabel.setText("Years :");
        otherDetailPanel.add(residentDurationYearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 83, -1, -1));

        residentDurationMonthsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        residentDurationMonthsLabel.setText("Months :");
        otherDetailPanel.add(residentDurationMonthsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 83, -1, -1));

        residentDurationDaysLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        residentDurationDaysLabel.setText("Days :");
        otherDetailPanel.add(residentDurationDaysLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 83, -1, -1));

        residentDurationYearFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        residentDurationYearFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        residentDurationYearFormattedTextField.setEnabled(false);
        residentDurationYearFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        residentDurationYearFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentDurationYearFormattedTextFieldActionPerformed(evt);
            }
        });
        otherDetailPanel.add(residentDurationYearFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 80, 53, -1));

        residentDurationMonthsFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        residentDurationMonthsFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        residentDurationMonthsFormattedTextField.setEnabled(false);
        residentDurationMonthsFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        residentDurationMonthsFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentDurationMonthsFormattedTextFieldActionPerformed(evt);
            }
        });
        otherDetailPanel.add(residentDurationMonthsFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 80, 49, -1));

        residentDurationDaysFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        residentDurationDaysFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        residentDurationDaysFormattedTextField.setEnabled(false);
        residentDurationDaysFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        residentDurationDaysFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentDurationDaysFormattedTextFieldActionPerformed(evt);
            }
        });
        otherDetailPanel.add(residentDurationDaysFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 80, 48, -1));

        jLayeredPane1.add(otherDetailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 590, 200));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 610, 110, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jLayeredPane1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 10, 590));

        incomeTaxPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Income Tax", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        incomeTaxPanel.setOpaque(false);
        incomeTaxPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yearLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearLabel.setText("Year :");
        incomeTaxPanel.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 33, -1, -1));

        yearComboBox.setBackground(new java.awt.Color(233, 231, 231));
        yearComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select Year>" }));
        yearComboBox.setEnabled(false);
        yearComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearComboBoxItemStateChanged(evt);
            }
        });
        incomeTaxPanel.add(yearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 30, 110, -1));

        taxableIncomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taxableIncomeLabel.setText("Taxable Income :");
        incomeTaxPanel.add(taxableIncomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 67, -1, -1));

        taxLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taxLabel.setText("Tax :");
        incomeTaxPanel.add(taxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 105, -1, -1));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        taxTable.setBackground(new java.awt.Color(233, 231, 231));
        taxTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taxTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Taxable Income", "Tax"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(taxTable);

        incomeTaxPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 133, 362, 117));

        taxableIncomeFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        taxableIncomeFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        taxableIncomeFormattedTextField.setEnabled(false);
        taxableIncomeFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taxableIncomeFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxableIncomeFormattedTextFieldActionPerformed(evt);
            }
        });
        incomeTaxPanel.add(taxableIncomeFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 64, 110, -1));

        taxFormattedTextField.setBackground(new java.awt.Color(233, 231, 231));
        taxFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        taxFormattedTextField.setEnabled(false);
        taxFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taxFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxFormattedTextFieldActionPerformed(evt);
            }
        });
        incomeTaxPanel.add(taxFormattedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 98, 110, -1));

        jLayeredPane1.add(incomeTaxPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 390, 260));

        bankersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Bankers' Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N
        bankersPanel.setOpaque(false);
        bankersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bankNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bankNameLabel.setText("Bank name :");
        bankersPanel.add(bankNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 33, -1, -1));

        bankAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bankAddressLabel.setText("Address :");
        bankersPanel.add(bankAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 67, -1, -1));

        accountNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accountNoLabel.setText("Account No :");
        bankersPanel.add(accountNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 101, -1, -1));

        bankNameTextField.setBackground(new java.awt.Color(233, 231, 231));
        bankNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bankNameTextField.setEnabled(false);
        bankNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankNameTextFieldActionPerformed(evt);
            }
        });
        bankersPanel.add(bankNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 30, 262, -1));

        addressTextField.setBackground(new java.awt.Color(233, 231, 231));
        addressTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressTextField.setEnabled(false);
        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });
        bankersPanel.add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 64, 262, -1));

        accNoTextField.setBackground(new java.awt.Color(233, 231, 231));
        accNoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accNoTextField.setEnabled(false);
        accNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoTextFieldActionPerformed(evt);
            }
        });
        bankersPanel.add(accNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 98, 167, -1));

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bankTable.setBackground(new java.awt.Color(233, 231, 231));
        bankTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bankTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bank Name", "Address", "Acc. No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bankTable);

        bankersPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 127, 360, 110));

        jLayeredPane1.add(bankersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 390, 250));
        jLayeredPane1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 650));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        if (nameTextField.getText().length() > 0) {
            nicFormattedTextField.setEnabled(true);
            nicFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void nameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyReleased
        String name = nameTextField.getText();
        boolean res = Validation.validateNameWithInitials(evt);

        if (!res) {
            String newName = name.substring(0, name.length() - 1);
            nameTextField.setText(newName);
        }
    }//GEN-LAST:event_nameTextFieldKeyReleased

    private void citizenshipTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizenshipTextFieldActionPerformed
        if (citizenshipTextField.getText().length() > 0) {
            privateAddressTextField.setEnabled(true);
            privateAddressTextField.requestFocus();
        }
    }//GEN-LAST:event_citizenshipTextFieldActionPerformed

    private void citizenshipTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_citizenshipTextFieldKeyReleased
        String citizenship = citizenshipTextField.getText();
        boolean res = Validation.validateNameWithInitials(evt);

        if (!res) {
            String newCitizenship = citizenship.substring(0, citizenship.length() - 1);
            citizenshipTextField.setText(newCitizenship);
        }
    }//GEN-LAST:event_citizenshipTextFieldKeyReleased

    private void nicFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicFormattedTextFieldActionPerformed
        citizenshipTextField.setEnabled(true);
        citizenshipTextField.requestFocus();
    }//GEN-LAST:event_nicFormattedTextFieldActionPerformed

    private void privateAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privateAddressTextFieldActionPerformed
        if (privateAddressTextField.getText().length() > 0) {
            officialAddressTextField.setEnabled(true);
            officialAddressTextField.requestFocus();
        }
    }//GEN-LAST:event_privateAddressTextFieldActionPerformed

    private void officialAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officialAddressTextFieldActionPerformed
        if (officialAddressTextField.getText().length() > 0) {
            ownerRadioButton.requestFocus();
        }
    }//GEN-LAST:event_officialAddressTextFieldActionPerformed

    private void ownerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerRadioButtonActionPerformed
        if (ownerRadioButton.isSelected()) {
            statusInPvt = ownerRadioButton.getText();
            telNoFormattedTextField.setEnabled(true);
            telNoFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_ownerRadioButtonActionPerformed

    private void tenantRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantRadioButtonActionPerformed
        if (tenantRadioButton.isSelected()) {
            statusInPvt = tenantRadioButton.getText();
            telNoFormattedTextField.setEnabled(true);
            telNoFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_tenantRadioButtonActionPerformed

    private void boarderRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boarderRadioButtonActionPerformed
        if (boarderRadioButton.isSelected()) {
            statusInPvt = boarderRadioButton.getText();
            telNoFormattedTextField.setEnabled(true);
            telNoFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_boarderRadioButtonActionPerformed

    private void telNoFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telNoFormattedTextFieldActionPerformed
        occupationTextField.setEnabled(true);
        occupationTextField.requestFocus();
    }//GEN-LAST:event_telNoFormattedTextFieldActionPerformed

    private void occupationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationTextFieldActionPerformed
        if (occupationTextField.getText().length() > 0) {
            soleProprietorshipRadioButton.requestFocus();
        }
    }//GEN-LAST:event_occupationTextFieldActionPerformed

    private void occupationTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_occupationTextFieldKeyReleased
        String occupation = occupationTextField.getText();
        boolean res = Validation.validateNameWithInitials(evt);

        if (!res) {
            String newOccupation = occupation.substring(0, occupation.length() - 1);
            occupationTextField.setText(newOccupation);
        }
    }//GEN-LAST:event_occupationTextFieldKeyReleased

    private void soleProprietorshipRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soleProprietorshipRadioButtonActionPerformed
        if (soleProprietorshipRadioButton.isSelected()) {
            organizationType = soleProprietorshipRadioButton.getText();
            residentDurationYearFormattedTextField.setEnabled(true);
            residentDurationYearFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_soleProprietorshipRadioButtonActionPerformed

    private void partnershipRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partnershipRadioButtonActionPerformed
        if (partnershipRadioButton.isSelected()) {
            organizationType = partnershipRadioButton.getText();
            residentDurationYearFormattedTextField.setEnabled(true);
            residentDurationYearFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_partnershipRadioButtonActionPerformed

    private void limitedComanyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitedComanyRadioButtonActionPerformed
        if (limitedComanyRadioButton.isSelected()) {
            organizationType = limitedComanyRadioButton.getText();
            residentDurationYearFormattedTextField.setEnabled(true);
            residentDurationYearFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_limitedComanyRadioButtonActionPerformed

    private void marriedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marriedRadioButtonActionPerformed
        if (marriedRadioButton.isSelected()) {
            maritalStatus = marriedRadioButton.getText();
            incomeSourceTextField.setEnabled(true);
            incomeSourceTextField.requestFocus();
        }
    }//GEN-LAST:event_marriedRadioButtonActionPerformed

    private void unmarriedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unmarriedRadioButtonActionPerformed
        if (unmarriedRadioButton.isSelected()) {
            maritalStatus = unmarriedRadioButton.getText();
            incomeSourceTextField.setEnabled(true);
            incomeSourceTextField.requestFocus();
        }
    }//GEN-LAST:event_unmarriedRadioButtonActionPerformed

    private void incomeSourceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeSourceTextFieldActionPerformed
        if (incomeSourceTextField.getText().length() > 0) {
            monthlyIncomeFormattedTextField.setEnabled(true);
            monthlyIncomeFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_incomeSourceTextFieldActionPerformed

    private void incomeSourceTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_incomeSourceTextFieldKeyReleased
        String incomeSource = incomeSourceTextField.getText();
        boolean res = Validation.validateNameWithInitials(evt);

        if (!res) {
            String newIncomeSource = incomeSource.substring(0, incomeSource.length() - 1);
            incomeSourceTextField.setText(newIncomeSource);
        }
    }//GEN-LAST:event_incomeSourceTextFieldKeyReleased

    private void monthlyIncomeFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyIncomeFormattedTextFieldActionPerformed
        yearComboBox.setEnabled(true);
        yearComboBox.requestFocus();
    }//GEN-LAST:event_monthlyIncomeFormattedTextFieldActionPerformed

    private void residentDurationYearFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentDurationYearFormattedTextFieldActionPerformed
        residentDurationMonthsFormattedTextField.setEnabled(true);
        residentDurationMonthsFormattedTextField.requestFocus();
    }//GEN-LAST:event_residentDurationYearFormattedTextFieldActionPerformed

    private void residentDurationMonthsFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentDurationMonthsFormattedTextFieldActionPerformed
        if (Integer.parseInt(residentDurationMonthsFormattedTextField.getText()) < 12) {
            residentDurationMonthsFormattedTextField.setForeground(Color.BLACK);
            residentDurationDaysFormattedTextField.setEnabled(true);
            residentDurationDaysFormattedTextField.requestFocus();
        } else {
            residentDurationMonthsFormattedTextField.setForeground(Color.red);
        }
    }//GEN-LAST:event_residentDurationMonthsFormattedTextFieldActionPerformed

    private void residentDurationDaysFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentDurationDaysFormattedTextFieldActionPerformed
        if (Integer.parseInt(residentDurationDaysFormattedTextField.getText()) < 31) {
            residentDurationDaysFormattedTextField.setForeground(Color.black);
            marriedRadioButton.requestFocus();
        } else {
            residentDurationDaysFormattedTextField.setForeground(Color.red);
        }
    }//GEN-LAST:event_residentDurationDaysFormattedTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String guarentorId = guarantorIdTextField.getText();
        String name = nameTextField.getText();
        String nic = nicFormattedTextField.getText();
        String citizenship = citizenshipTextField.getText();
        String privateAddress = privateAddressTextField.getText();
        String officialAddress = officialAddressTextField.getText();
        String telNo = telNoFormattedTextField.getText();
        String occupation = occupationTextField.getText();
        String residentDuration = residentDurationYearFormattedTextField.getText() + " Years " + residentDurationMonthsFormattedTextField.getText() + " Months " + residentDurationDaysFormattedTextField.getText() + " Days";
        String birthYear = nic.substring(0, 2);
        int birthYearI = 1900 + Integer.parseInt(birthYear);
        int age = currentYear - birthYearI;
        String incomeSource = incomeSourceTextField.getText();
        double monthlyIncome = Double.parseDouble(monthlyIncomeFormattedTextField.getText());

        //get guarentor details
        Guarentor guarentor = new Guarentor(leasingNo, guarentorId, name, nic, occupation, privateAddress, officialAddress, telNo, organizationType, residentDuration, statusInPvt, citizenship, age, maritalStatus, incomeSource, monthlyIncome);

        //get taxTable details
        DefaultTableModel taxdtm = (DefaultTableModel) taxTable.getModel();
        ArrayList<GuarentorIncomeTax> taxList = new ArrayList<GuarentorIncomeTax>();

        for (int i = 0; i < taxTable.getRowCount(); i++) {
            GuarentorIncomeTax tax = new GuarentorIncomeTax();
            tax.setGuarentorId(guarentorId);
            String yearString = taxdtm.getValueAt(i, 0).toString();
            tax.setYear((int) taxdtm.getValueAt(i, 0));
            String taxableIncomeString = (String) taxdtm.getValueAt(i, 1);
            tax.setTaxableIncome(Double.parseDouble(taxableIncomeString));
            String taxPaidString = (String) taxdtm.getValueAt(i, 2);
            tax.setTaxPaid(Double.parseDouble(taxPaidString));
            taxList.add(tax);
        }

        //get bankTable details
        DefaultTableModel bankdtm = (DefaultTableModel) bankTable.getModel();
        ArrayList<GuarentorBankers> bankerList = new ArrayList<GuarentorBankers>();

        for (int i = 0; i < bankTable.getRowCount(); i++) {
            GuarentorBankers banker = new GuarentorBankers();
            banker.setGuarentorId(guarentorId);
            banker.setBankName((String) bankdtm.getValueAt(i, 0));
            banker.setAddress((String) bankdtm.getValueAt(i, 1));
            banker.setAccountNo((String) bankdtm.getValueAt(i, 2));
            bankerList.add(banker);
        }

        try {
            ServerConnector serverConnector = ServerConnector.getServerConnector();
            GuarentorController guarentorController = serverConnector.getGuarentorController();
            GuarentorBankersController bankersController = serverConnector.getGuarentorBankersController();
            GuarentorIncomeTaxController incomeTaxController = serverConnector.getGuarentorIncomeTaxController();

            boolean res1 = guarentorController.addGuarentor(guarentor);
            if (res1) {
                boolean res2 = incomeTaxController.addIncomeTax(taxList);
                if (res2) {
                    boolean res3 = bankersController.addBankers(bankerList);
                    if (res3) {
                        JOptionPane.showMessageDialog(this, name + "'s (1st Guarentor) details successfully added.", "Message", JOptionPane.PLAIN_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add " + name + "'s (1st Guarentor) details.", "Message", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddFirstGuarantorForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void yearComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearComboBoxItemStateChanged
        try {
            int year = (int) yearComboBox.getSelectedItem();
            taxableIncomeFormattedTextField.setEnabled(true);
            taxableIncomeFormattedTextField.requestFocus();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_yearComboBoxItemStateChanged

    private void taxableIncomeFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxableIncomeFormattedTextFieldActionPerformed
        taxFormattedTextField.setEnabled(true);
        taxFormattedTextField.setText(null);
        taxFormattedTextField.requestFocus();
    }//GEN-LAST:event_taxableIncomeFormattedTextFieldActionPerformed

    private void taxFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxFormattedTextFieldActionPerformed
        if (taxTable.getRowCount() < 2) {
            DefaultTableModel dtm = (DefaultTableModel) taxTable.getModel();
            dtm.addRow(new Object[]{yearComboBox.getSelectedItem(), taxableIncomeFormattedTextField.getText(), taxFormattedTextField.getText()});
            yearComboBox.requestFocus();
            taxableIncomeFormattedTextField.setText(null);
            taxFormattedTextField.setText(null);
            taxableIncomeFormattedTextField.setEnabled(false);
            taxFormattedTextField.setEnabled(false);
        } else {
            DefaultTableModel dtm = (DefaultTableModel) taxTable.getModel();
            dtm.addRow(new Object[]{yearComboBox.getSelectedItem(), taxableIncomeFormattedTextField.getText(), taxFormattedTextField.getText()});
            taxableIncomeFormattedTextField.setText(null);
            taxFormattedTextField.setText(null);
            taxableIncomeFormattedTextField.setEnabled(false);
            taxFormattedTextField.setEnabled(false);
            bankNameTextField.setEnabled(true);
            bankNameTextField.requestFocus();
        }
    }//GEN-LAST:event_taxFormattedTextFieldActionPerformed

    private void bankNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankNameTextFieldActionPerformed
        if (bankNameTextField.getText().length() > 0) {
            addressTextField.setEnabled(true);
            addressTextField.requestFocus();
        }
    }//GEN-LAST:event_bankNameTextFieldActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        if (addressTextField.getText().length() > 0) {
            accNoTextField.setEnabled(true);
            accNoTextField.requestFocus();
        }
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void accNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoTextFieldActionPerformed
        if (accNoTextField.getText().length() > 0) {
            DefaultTableModel dtm = (DefaultTableModel) bankTable.getModel();
            dtm.addRow(new Object[]{bankNameTextField.getText(), addressTextField.getText(), accNoTextField.getText()});
            bankNameTextField.setText(null);
            addressTextField.setText(null);
            accNoTextField.setText(null);
        }
    }//GEN-LAST:event_accNoTextFieldActionPerformed
    
    public static void setLeasingNo(String no){
        leasingNo = no;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFirstGuarantorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFirstGuarantorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFirstGuarantorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFirstGuarantorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFirstGuarantorForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNoTextField;
    private javax.swing.JLabel accountNoLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel bankAddressLabel;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JTable bankTable;
    private javax.swing.JPanel bankersPanel;
    private javax.swing.JRadioButton boarderRadioButton;
    private javax.swing.JLabel citizenshipLabel;
    private javax.swing.JTextField citizenshipTextField;
    private javax.swing.JPanel contactDeatailPanel;
    private javax.swing.JLabel guarantorIdLabel;
    private javax.swing.JTextField guarantorIdTextField;
    private javax.swing.JLabel incomeSourceLabel;
    private javax.swing.JTextField incomeSourceTextField;
    private javax.swing.JPanel incomeTaxPanel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton limitedComanyRadioButton;
    private javax.swing.JLabel maritalLabel;
    private javax.swing.JRadioButton marriedRadioButton;
    private javax.swing.JFormattedTextField monthlyIncomeFormattedTextField;
    private javax.swing.JLabel monthlyIncomeLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JFormattedTextField nicFormattedTextField;
    private javax.swing.JLabel nicLabel;
    private javax.swing.JLabel occupationLabel;
    private javax.swing.JTextField occupationTextField;
    private javax.swing.JLabel officialAddressLabel;
    private javax.swing.JTextField officialAddressTextField;
    private javax.swing.JLabel organizationTypeLabel;
    private javax.swing.JPanel otherDetailPanel;
    private javax.swing.JRadioButton ownerRadioButton;
    private javax.swing.JRadioButton partnershipRadioButton;
    private javax.swing.JTextField privateAddressTextField;
    private javax.swing.JLabel pvtAddressLabel;
    private javax.swing.JPanel recognitionDetailPanel;
    private javax.swing.JFormattedTextField residentDurationDaysFormattedTextField;
    private javax.swing.JLabel residentDurationDaysLabel;
    private javax.swing.JLabel residentDurationLabel;
    private javax.swing.JFormattedTextField residentDurationMonthsFormattedTextField;
    private javax.swing.JLabel residentDurationMonthsLabel;
    private javax.swing.JFormattedTextField residentDurationYearFormattedTextField;
    private javax.swing.JLabel residentDurationYearLabel;
    private javax.swing.JRadioButton soleProprietorshipRadioButton;
    private javax.swing.JLabel statusPvtLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JFormattedTextField taxFormattedTextField;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JTable taxTable;
    private javax.swing.JFormattedTextField taxableIncomeFormattedTextField;
    private javax.swing.JLabel taxableIncomeLabel;
    private javax.swing.JFormattedTextField telNoFormattedTextField;
    private javax.swing.JLabel telNoLabel;
    private javax.swing.JRadioButton tenantRadioButton;
    private javax.swing.JRadioButton unmarriedRadioButton;
    private javax.swing.JComboBox yearComboBox;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
