/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.guarantor;

import java.awt.Color;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lbfinance.serverConnector.ServerConnector;
import lbfinance.important.Validation;
import lbfinancecommon.controller.GuarentorBankersController;
import lbfinancecommon.controller.GuarentorController;
import lbfinancecommon.controller.GuarentorIncomeTaxController;
import lbfinancecommon.model.Guarentor;
import lbfinancecommon.model.GuarentorBankers;
import lbfinancecommon.model.GuarentorIncomeTax;

/**
 *
 * @author cmjd
 */
public class AddGuaranteeForm2 extends javax.swing.JDialog {

    private String clientId;
    private String statusInPvt;
    private String maritalStatus;
    private String organizationType;
    private int currentYear;

    /**
     * Creates new form AddGuaranteeForm
     */
    public AddGuaranteeForm2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //setSize(Toolkit.getDefaultToolkit().getScreenSize());

        Calendar c = Calendar.getInstance();
        currentYear = c.getWeekYear();

        yearComboBox.addItem(currentYear - 3);
        yearComboBox.addItem(currentYear - 2);
        yearComboBox.addItem(currentYear - 1);
        taxableIncomeFormattedTextField.setEnabled(false);

        nameTextField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusInPvtButtonGroup = new javax.swing.ButtonGroup();
        organizationTypeButtonGroup = new javax.swing.ButtonGroup();
        maritalStatusButtonGroup = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        recognitionDetailPanel = new javax.swing.JPanel();
        guarantorIdLabel = new javax.swing.JLabel();
        guarantorIdTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        nicLabel = new javax.swing.JLabel();
        citizenshipLabel = new javax.swing.JLabel();
        citizenshipTextField = new javax.swing.JTextField();
        nicFormattedTextField = new javax.swing.JFormattedTextField();
        contactDeatailPanel = new javax.swing.JPanel();
        pvtAddressLabel = new javax.swing.JLabel();
        privateAddressTextField = new javax.swing.JTextField();
        officialAddressLabel = new javax.swing.JLabel();
        officialAddressTextField = new javax.swing.JTextField();
        statusPvtLabel = new javax.swing.JLabel();
        telNoLabel = new javax.swing.JLabel();
        ownerRadioButton = new javax.swing.JRadioButton();
        tenantRadioButton = new javax.swing.JRadioButton();
        boarderRadioButton = new javax.swing.JRadioButton();
        telNoFormattedTextField = new javax.swing.JFormattedTextField();
        otherDetailPanel = new javax.swing.JPanel();
        occupationLabel = new javax.swing.JLabel();
        occupationTextField = new javax.swing.JTextField();
        organizationTypeLabel = new javax.swing.JLabel();
        soleProprietorshipRadioButton = new javax.swing.JRadioButton();
        partnershipRadioButton = new javax.swing.JRadioButton();
        limitedComanyRadioButton = new javax.swing.JRadioButton();
        residentDurationLabel = new javax.swing.JLabel();
        maritalLabel = new javax.swing.JLabel();
        marriedRadioButton = new javax.swing.JRadioButton();
        unmarriedRadioButton = new javax.swing.JRadioButton();
        incomeSourceLabel = new javax.swing.JLabel();
        incomeSourceTextField = new javax.swing.JTextField();
        monthlyIncomeLabel = new javax.swing.JLabel();
        monthlyIncomeFormattedTextField = new javax.swing.JFormattedTextField();
        residentDurationYearLabel = new javax.swing.JLabel();
        residentDurationMonthsLabel = new javax.swing.JLabel();
        residentDurationDaysLabel = new javax.swing.JLabel();
        residentDurationYearFormattedTextField = new javax.swing.JFormattedTextField();
        residentDurationMonthsFormattedTextField = new javax.swing.JFormattedTextField();
        residentDurationDaysFormattedTextField = new javax.swing.JFormattedTextField();
        submitButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        incomeTaxPanel = new javax.swing.JPanel();
        yearLabel = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox();
        taxableIncomeLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taxTable = new javax.swing.JTable();
        taxableIncomeFormattedTextField = new javax.swing.JFormattedTextField();
        taxFormattedTextField = new javax.swing.JFormattedTextField();
        bankersPanel = new javax.swing.JPanel();
        bankNameLabel = new javax.swing.JLabel();
        bankAddressLabel = new javax.swing.JLabel();
        accountNoLabel = new javax.swing.JLabel();
        bankNameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        accNoTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bankTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        recognitionDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recognition Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        recognitionDetailPanel.setOpaque(false);

        guarantorIdLabel.setText("Guarantor ID :");

        guarantorIdTextField.setEditable(false);

        nameLabel.setText("Guarantor Name:");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyReleased(evt);
            }
        });

        nicLabel.setText("NIC No :");

        citizenshipLabel.setText("Citizenship :");

        citizenshipTextField.setEnabled(false);
        citizenshipTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizenshipTextFieldActionPerformed(evt);
            }
        });
        citizenshipTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                citizenshipTextFieldKeyReleased(evt);
            }
        });

        try {
            nicFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########v")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nicFormattedTextField.setEnabled(false);
        nicFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicFormattedTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recognitionDetailPanelLayout = new javax.swing.GroupLayout(recognitionDetailPanel);
        recognitionDetailPanel.setLayout(recognitionDetailPanelLayout);
        recognitionDetailPanelLayout.setHorizontalGroup(
            recognitionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recognitionDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recognitionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(citizenshipLabel)
                    .addComponent(nicLabel)
                    .addComponent(nameLabel)
                    .addComponent(guarantorIdLabel))
                .addGap(73, 73, 73)
                .addGroup(recognitionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guarantorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(recognitionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nicFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(citizenshipTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        recognitionDetailPanelLayout.setVerticalGroup(
            recognitionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recognitionDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recognitionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guarantorIdLabel)
                    .addComponent(guarantorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(recognitionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recognitionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nicLabel)
                    .addComponent(nicFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recognitionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(citizenshipLabel)
                    .addComponent(citizenshipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(recognitionDetailPanel);
        recognitionDetailPanel.setBounds(10, 70, 560, 140);

        contactDeatailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        pvtAddressLabel.setText("Private Address :");

        privateAddressTextField.setEnabled(false);
        privateAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privateAddressTextFieldActionPerformed(evt);
            }
        });

        officialAddressLabel.setText("Official Address :");

        officialAddressTextField.setEnabled(false);
        officialAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officialAddressTextFieldActionPerformed(evt);
            }
        });

        statusPvtLabel.setText("Status in Private Address :");

        telNoLabel.setText("Tel. No :");

        statusInPvtButtonGroup.add(ownerRadioButton);
        ownerRadioButton.setText("Owner");
        ownerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerRadioButtonActionPerformed(evt);
            }
        });

        statusInPvtButtonGroup.add(tenantRadioButton);
        tenantRadioButton.setText("Tenant");
        tenantRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantRadioButtonActionPerformed(evt);
            }
        });

        statusInPvtButtonGroup.add(boarderRadioButton);
        boarderRadioButton.setText("Boarder");
        boarderRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boarderRadioButtonActionPerformed(evt);
            }
        });

        try {
            telNoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0##-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telNoFormattedTextField.setEnabled(false);
        telNoFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telNoFormattedTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contactDeatailPanelLayout = new javax.swing.GroupLayout(contactDeatailPanel);
        contactDeatailPanel.setLayout(contactDeatailPanelLayout);
        contactDeatailPanelLayout.setHorizontalGroup(
            contactDeatailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDeatailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactDeatailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactDeatailPanelLayout.createSequentialGroup()
                        .addComponent(pvtAddressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(privateAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(contactDeatailPanelLayout.createSequentialGroup()
                        .addGroup(contactDeatailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contactDeatailPanelLayout.createSequentialGroup()
                                .addGroup(contactDeatailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusPvtLabel)
                                    .addComponent(telNoLabel))
                                .addGap(30, 30, 30)
                                .addGroup(contactDeatailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telNoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(contactDeatailPanelLayout.createSequentialGroup()
                                        .addComponent(ownerRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(tenantRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(boarderRadioButton))))
                            .addGroup(contactDeatailPanelLayout.createSequentialGroup()
                                .addComponent(officialAddressLabel)
                                .addGap(76, 76, 76)
                                .addComponent(officialAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        contactDeatailPanelLayout.setVerticalGroup(
            contactDeatailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDeatailPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(contactDeatailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pvtAddressLabel)
                    .addComponent(privateAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contactDeatailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(officialAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(officialAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contactDeatailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusPvtLabel)
                    .addComponent(ownerRadioButton)
                    .addComponent(tenantRadioButton)
                    .addComponent(boarderRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contactDeatailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telNoLabel)
                    .addComponent(telNoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jLayeredPane1.add(contactDeatailPanel);
        contactDeatailPanel.setBounds(10, 220, 560, 150);

        otherDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        occupationLabel.setText("Occupation :");

        occupationTextField.setEnabled(false);
        occupationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationTextFieldActionPerformed(evt);
            }
        });
        occupationTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                occupationTextFieldKeyReleased(evt);
            }
        });

        organizationTypeLabel.setText("Organization Type :");

        organizationTypeButtonGroup.add(soleProprietorshipRadioButton);
        soleProprietorshipRadioButton.setText("Sole Proprietorship");
        soleProprietorshipRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soleProprietorshipRadioButtonActionPerformed(evt);
            }
        });

        organizationTypeButtonGroup.add(partnershipRadioButton);
        partnershipRadioButton.setText("Partnership");
        partnershipRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partnershipRadioButtonActionPerformed(evt);
            }
        });

        organizationTypeButtonGroup.add(limitedComanyRadioButton);
        limitedComanyRadioButton.setText("Limited Company");
        limitedComanyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitedComanyRadioButtonActionPerformed(evt);
            }
        });

        residentDurationLabel.setText("Resident Duration :");

        maritalLabel.setText("Marital Status :");

        maritalStatusButtonGroup.add(marriedRadioButton);
        marriedRadioButton.setText("Married");
        marriedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marriedRadioButtonActionPerformed(evt);
            }
        });

        maritalStatusButtonGroup.add(unmarriedRadioButton);
        unmarriedRadioButton.setText("Unmarried");
        unmarriedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unmarriedRadioButtonActionPerformed(evt);
            }
        });

        incomeSourceLabel.setText("Income Source :");

        incomeSourceTextField.setEnabled(false);
        incomeSourceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeSourceTextFieldActionPerformed(evt);
            }
        });
        incomeSourceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                incomeSourceTextFieldKeyReleased(evt);
            }
        });

        monthlyIncomeLabel.setText("Totally Monthly Income :");

        monthlyIncomeFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        monthlyIncomeFormattedTextField.setEnabled(false);
        monthlyIncomeFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyIncomeFormattedTextFieldActionPerformed(evt);
            }
        });

        residentDurationYearLabel.setText("Years :");

        residentDurationMonthsLabel.setText("Months :");

        residentDurationDaysLabel.setText("Days :");

        residentDurationYearFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        residentDurationYearFormattedTextField.setEnabled(false);
        residentDurationYearFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentDurationYearFormattedTextFieldActionPerformed(evt);
            }
        });

        residentDurationMonthsFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        residentDurationMonthsFormattedTextField.setEnabled(false);
        residentDurationMonthsFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentDurationMonthsFormattedTextFieldActionPerformed(evt);
            }
        });

        residentDurationDaysFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        residentDurationDaysFormattedTextField.setEnabled(false);
        residentDurationDaysFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentDurationDaysFormattedTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout otherDetailPanelLayout = new javax.swing.GroupLayout(otherDetailPanel);
        otherDetailPanel.setLayout(otherDetailPanelLayout);
        otherDetailPanelLayout.setHorizontalGroup(
            otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(otherDetailPanelLayout.createSequentialGroup()
                        .addComponent(occupationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(occupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherDetailPanelLayout.createSequentialGroup()
                        .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(otherDetailPanelLayout.createSequentialGroup()
                                    .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(residentDurationLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(maritalLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(incomeSourceLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(65, 65, 65))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, otherDetailPanelLayout.createSequentialGroup()
                                    .addComponent(monthlyIncomeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(otherDetailPanelLayout.createSequentialGroup()
                                .addComponent(organizationTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incomeSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthlyIncomeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(otherDetailPanelLayout.createSequentialGroup()
                                .addComponent(soleProprietorshipRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(partnershipRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(limitedComanyRadioButton))
                            .addGroup(otherDetailPanelLayout.createSequentialGroup()
                                .addComponent(marriedRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unmarriedRadioButton))
                            .addGroup(otherDetailPanelLayout.createSequentialGroup()
                                .addComponent(residentDurationYearLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentDurationYearFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(residentDurationMonthsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentDurationMonthsFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(residentDurationDaysLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(residentDurationDaysFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        otherDetailPanelLayout.setVerticalGroup(
            otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherDetailPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(occupationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(organizationTypeLabel)
                    .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(soleProprietorshipRadioButton)
                        .addComponent(partnershipRadioButton)
                        .addComponent(limitedComanyRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(residentDurationYearLabel)
                        .addComponent(residentDurationMonthsLabel)
                        .addComponent(residentDurationDaysLabel)
                        .addComponent(residentDurationYearFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(residentDurationMonthsFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(residentDurationDaysFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(residentDurationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maritalLabel)
                    .addComponent(marriedRadioButton)
                    .addComponent(unmarriedRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incomeSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incomeSourceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthlyIncomeLabel)
                    .addComponent(monthlyIncomeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 49, Short.MAX_VALUE))
        );

        jLayeredPane1.add(otherDetailPanel);
        otherDetailPanel.setBounds(10, 380, 560, 230);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(submitButton);
        submitButton.setBounds(880, 610, 110, 23);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jLayeredPane1.add(jSeparator1);
        jSeparator1.setBounds(580, 60, 10, 590);

        incomeTaxPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Income Tax"));

        yearLabel.setText("Year :");

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select Year>" }));
        yearComboBox.setEnabled(false);
        yearComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearComboBoxItemStateChanged(evt);
            }
        });

        taxableIncomeLabel.setText("Taxable Income :");

        taxLabel.setText("Tax :");

        taxTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Taxable Income", "Tax"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(taxTable);

        taxableIncomeFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        taxableIncomeFormattedTextField.setEnabled(false);
        taxableIncomeFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxableIncomeFormattedTextFieldActionPerformed(evt);
            }
        });

        taxFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        taxFormattedTextField.setEnabled(false);
        taxFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxFormattedTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout incomeTaxPanelLayout = new javax.swing.GroupLayout(incomeTaxPanel);
        incomeTaxPanel.setLayout(incomeTaxPanelLayout);
        incomeTaxPanelLayout.setHorizontalGroup(
            incomeTaxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeTaxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeTaxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(incomeTaxPanelLayout.createSequentialGroup()
                        .addGroup(incomeTaxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxableIncomeLabel)
                            .addComponent(yearLabel)
                            .addComponent(taxLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(incomeTaxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(taxableIncomeFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 110, Short.MAX_VALUE)
                            .addComponent(taxFormattedTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        incomeTaxPanelLayout.setVerticalGroup(
            incomeTaxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeTaxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeTaxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(incomeTaxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxableIncomeLabel)
                    .addComponent(taxableIncomeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(incomeTaxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(incomeTaxPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(taxLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(incomeTaxPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taxFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322))
        );

        jLayeredPane1.add(incomeTaxPanel);
        incomeTaxPanel.setBounds(600, 70, 390, 260);

        bankersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bankers' Details"));

        bankNameLabel.setText("Bank name :");

        bankAddressLabel.setText("Address :");

        accountNoLabel.setText("Account No :");

        bankNameTextField.setEnabled(false);
        bankNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankNameTextFieldActionPerformed(evt);
            }
        });

        addressTextField.setEnabled(false);
        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });

        accNoTextField.setEnabled(false);
        accNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoTextFieldActionPerformed(evt);
            }
        });

        bankTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bank Name", "Address", "Acc. No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bankTable);

        javax.swing.GroupLayout bankersPanelLayout = new javax.swing.GroupLayout(bankersPanel);
        bankersPanel.setLayout(bankersPanelLayout);
        bankersPanelLayout.setHorizontalGroup(
            bankersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bankersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bankersPanelLayout.createSequentialGroup()
                        .addGroup(bankersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankNameLabel)
                            .addComponent(bankAddressLabel))
                        .addGap(21, 21, 21)
                        .addGroup(bankersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(bankNameTextField)))
                    .addGroup(bankersPanelLayout.createSequentialGroup()
                        .addComponent(accountNoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(accNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                .addContainerGap())
        );
        bankersPanelLayout.setVerticalGroup(
            bankersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bankersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNameLabel)
                    .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bankersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankAddressLabel)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bankersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNoLabel)
                    .addComponent(accNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(bankersPanel);
        bankersPanel.setBounds(600, 340, 390, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        if (nameTextField.getText().length() > 0) {
            nicFormattedTextField.setEnabled(true);
            nicFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void nameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyReleased
        String name = nameTextField.getText();
        boolean res = Validation.validateNameWithInitials(evt);

        if (!res) {
            String newName = name.substring(0, name.length() - 1);
            nameTextField.setText(newName);
        }
    }//GEN-LAST:event_nameTextFieldKeyReleased

    private void nicFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicFormattedTextFieldActionPerformed
        citizenshipTextField.setEnabled(true);
        citizenshipTextField.requestFocus();
    }//GEN-LAST:event_nicFormattedTextFieldActionPerformed

    private void citizenshipTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_citizenshipTextFieldKeyReleased
        String citizenship = citizenshipTextField.getText();
        boolean res = Validation.validateNameWithInitials(evt);

        if (!res) {
            String newCitizenship = citizenship.substring(0, citizenship.length() - 1);
            citizenshipTextField.setText(newCitizenship);
        }
    }//GEN-LAST:event_citizenshipTextFieldKeyReleased

    private void citizenshipTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizenshipTextFieldActionPerformed
        if (citizenshipTextField.getText().length() > 0) {
            privateAddressTextField.setEnabled(true);
            privateAddressTextField.requestFocus();
        }
    }//GEN-LAST:event_citizenshipTextFieldActionPerformed

    private void privateAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privateAddressTextFieldActionPerformed
        if (privateAddressTextField.getText().length() > 0) {
            officialAddressTextField.setEnabled(true);
            officialAddressTextField.requestFocus();
        }
    }//GEN-LAST:event_privateAddressTextFieldActionPerformed

    private void officialAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officialAddressTextFieldActionPerformed
        if (officialAddressTextField.getText().length() > 0) {
            ownerRadioButton.requestFocus();
        }
    }//GEN-LAST:event_officialAddressTextFieldActionPerformed

    private void ownerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerRadioButtonActionPerformed
        if (ownerRadioButton.isSelected()) {
            statusInPvt = ownerRadioButton.getText();
            telNoFormattedTextField.setEnabled(true);
            telNoFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_ownerRadioButtonActionPerformed

    private void tenantRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantRadioButtonActionPerformed
        if (tenantRadioButton.isSelected()) {
            statusInPvt = tenantRadioButton.getText();
            telNoFormattedTextField.setEnabled(true);
            telNoFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_tenantRadioButtonActionPerformed

    private void boarderRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boarderRadioButtonActionPerformed
        if (boarderRadioButton.isSelected()) {
            statusInPvt = boarderRadioButton.getText();
            telNoFormattedTextField.setEnabled(true);
            telNoFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_boarderRadioButtonActionPerformed

    private void telNoFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telNoFormattedTextFieldActionPerformed
        occupationTextField.setEnabled(true);
        occupationTextField.requestFocus();
    }//GEN-LAST:event_telNoFormattedTextFieldActionPerformed

    private void occupationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationTextFieldActionPerformed
        if (occupationTextField.getText().length() > 0) {
            soleProprietorshipRadioButton.requestFocus();
        }
    }//GEN-LAST:event_occupationTextFieldActionPerformed

    private void soleProprietorshipRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soleProprietorshipRadioButtonActionPerformed
        if (soleProprietorshipRadioButton.isSelected()) {
            organizationType = soleProprietorshipRadioButton.getText();
            residentDurationYearFormattedTextField.setEnabled(true);
            residentDurationYearFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_soleProprietorshipRadioButtonActionPerformed

    private void partnershipRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partnershipRadioButtonActionPerformed
        if (partnershipRadioButton.isSelected()) {
            organizationType = partnershipRadioButton.getText();
            residentDurationYearFormattedTextField.setEnabled(true);
            residentDurationYearFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_partnershipRadioButtonActionPerformed

    private void limitedComanyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitedComanyRadioButtonActionPerformed
        if (limitedComanyRadioButton.isSelected()) {
            organizationType = limitedComanyRadioButton.getText();
            residentDurationYearFormattedTextField.setEnabled(true);
            residentDurationYearFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_limitedComanyRadioButtonActionPerformed

    private void marriedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marriedRadioButtonActionPerformed
        if (marriedRadioButton.isSelected()) {
            maritalStatus = marriedRadioButton.getText();
            incomeSourceTextField.setEnabled(true);
            incomeSourceTextField.requestFocus();
        }
    }//GEN-LAST:event_marriedRadioButtonActionPerformed

    private void unmarriedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unmarriedRadioButtonActionPerformed
        if (unmarriedRadioButton.isSelected()) {
            maritalStatus = unmarriedRadioButton.getText();
            incomeSourceTextField.setEnabled(true);
            incomeSourceTextField.requestFocus();
        }
    }//GEN-LAST:event_unmarriedRadioButtonActionPerformed

    private void incomeSourceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeSourceTextFieldActionPerformed
        if (incomeSourceTextField.getText().length() > 0) {
            monthlyIncomeFormattedTextField.setEnabled(true);
            monthlyIncomeFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_incomeSourceTextFieldActionPerformed

    private void monthlyIncomeFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyIncomeFormattedTextFieldActionPerformed
        yearComboBox.setEnabled(true);
        yearComboBox.requestFocus();
    }//GEN-LAST:event_monthlyIncomeFormattedTextFieldActionPerformed

    private void yearComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearComboBoxItemStateChanged
        try {
            int year = (int) yearComboBox.getSelectedItem();
            taxableIncomeFormattedTextField.setEnabled(true);
            taxableIncomeFormattedTextField.requestFocus();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_yearComboBoxItemStateChanged

    private void taxableIncomeFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxableIncomeFormattedTextFieldActionPerformed
        taxFormattedTextField.setEnabled(true);
        taxFormattedTextField.setText(null);
        taxFormattedTextField.requestFocus();
    }//GEN-LAST:event_taxableIncomeFormattedTextFieldActionPerformed

    private void taxFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxFormattedTextFieldActionPerformed
        if (taxTable.getRowCount() < 2) {
            DefaultTableModel dtm = (DefaultTableModel) taxTable.getModel();
            dtm.addRow(new Object[]{yearComboBox.getSelectedItem(), taxableIncomeFormattedTextField.getText(), taxFormattedTextField.getText()});
            yearComboBox.requestFocus();
            taxableIncomeFormattedTextField.setText(null);
            taxFormattedTextField.setText(null);
            taxableIncomeFormattedTextField.setEnabled(false);
            taxFormattedTextField.setEnabled(false);
        } else {
            DefaultTableModel dtm = (DefaultTableModel) taxTable.getModel();
            dtm.addRow(new Object[]{yearComboBox.getSelectedItem(), taxableIncomeFormattedTextField.getText(), taxFormattedTextField.getText()});
            taxableIncomeFormattedTextField.setText(null);
            taxFormattedTextField.setText(null);
            taxableIncomeFormattedTextField.setEnabled(false);
            taxFormattedTextField.setEnabled(false);
            bankNameTextField.setEnabled(true);
            bankNameTextField.requestFocus();
        }
    }//GEN-LAST:event_taxFormattedTextFieldActionPerformed

    private void bankNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankNameTextFieldActionPerformed
        if (bankNameTextField.getText().length() > 0) {
            addressTextField.setEnabled(true);
            addressTextField.requestFocus();
        }
    }//GEN-LAST:event_bankNameTextFieldActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        if (addressTextField.getText().length() > 0) {
            accNoTextField.setEnabled(true);
            accNoTextField.requestFocus();
        }
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void accNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoTextFieldActionPerformed
        if (accNoTextField.getText().length() > 0) {
            DefaultTableModel dtm = (DefaultTableModel) bankTable.getModel();
            dtm.addRow(new Object[]{bankNameTextField.getText(), addressTextField.getText(), accNoTextField.getText()});
            bankNameTextField.setText(null);
            addressTextField.setText(null);
            accNoTextField.setText(null);
        }
    }//GEN-LAST:event_accNoTextFieldActionPerformed

    private void occupationTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_occupationTextFieldKeyReleased
        String occupation = occupationTextField.getText();
        boolean res = Validation.validateNameWithInitials(evt);

        if (!res) {
            String newOccupation = occupation.substring(0, occupation.length() - 1);
            occupationTextField.setText(newOccupation);
        }
    }//GEN-LAST:event_occupationTextFieldKeyReleased

    private void incomeSourceTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_incomeSourceTextFieldKeyReleased
        String incomeSource = incomeSourceTextField.getText();
        boolean res = Validation.validateNameWithInitials(evt);

        if (!res) {
            String newIncomeSource = incomeSource.substring(0, incomeSource.length() - 1);
            incomeSourceTextField.setText(newIncomeSource);
        }
    }//GEN-LAST:event_incomeSourceTextFieldKeyReleased

    private void residentDurationYearFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentDurationYearFormattedTextFieldActionPerformed
        residentDurationMonthsFormattedTextField.setEnabled(true);
        residentDurationMonthsFormattedTextField.requestFocus();
    }//GEN-LAST:event_residentDurationYearFormattedTextFieldActionPerformed

    private void residentDurationMonthsFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentDurationMonthsFormattedTextFieldActionPerformed
        if (Integer.parseInt(residentDurationMonthsFormattedTextField.getText()) < 12) {
            residentDurationMonthsFormattedTextField.setForeground(Color.BLACK);
            residentDurationDaysFormattedTextField.setEnabled(true);
            residentDurationDaysFormattedTextField.requestFocus();
        } else {
            residentDurationMonthsFormattedTextField.setForeground(Color.red);
        }
    }//GEN-LAST:event_residentDurationMonthsFormattedTextFieldActionPerformed

    private void residentDurationDaysFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentDurationDaysFormattedTextFieldActionPerformed
        if (Integer.parseInt(residentDurationDaysFormattedTextField.getText()) < 31) {
            residentDurationDaysFormattedTextField.setForeground(Color.black);
            marriedRadioButton.requestFocus();
        } else {
            residentDurationDaysFormattedTextField.setForeground(Color.red);
        }
    }//GEN-LAST:event_residentDurationDaysFormattedTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String guarentorId = guarantorIdTextField.getText();
        String name = nameTextField.getText();
        String nic = nicFormattedTextField.getText();
        String citizenship = citizenshipTextField.getText();
        String privateAddress = privateAddressTextField.getText();
        String officialAddress = officialAddressTextField.getText();
        String telNo = telNoFormattedTextField.getText();
        String occupation = occupationTextField.getText();
        String residentDuration = residentDurationYearFormattedTextField.getText() + " Years " + residentDurationMonthsFormattedTextField.getText() + " Months " + residentDurationDaysFormattedTextField.getText() + " Days";
        String birthYear = nic.substring(0, 2);
        int birthYearI = 1900 + Integer.parseInt(birthYear);
        int age = currentYear - birthYearI;
        String incomeSource = incomeSourceTextField.getText();
        double monthlyIncome = Double.parseDouble(monthlyIncomeFormattedTextField.getText());

        //get guarentor details
        Guarentor guarentor = new Guarentor(clientId, guarentorId, name, nic, occupation, privateAddress, officialAddress, telNo, organizationType, residentDuration, statusInPvt, citizenship, age, maritalStatus, incomeSource, monthlyIncome);

        //get taxTable details
        DefaultTableModel taxdtm = (DefaultTableModel) taxTable.getModel();
        ArrayList<GuarentorIncomeTax> taxList = new ArrayList<GuarentorIncomeTax>();

        for (int i = 0; i < taxTable.getRowCount(); i++) {
            GuarentorIncomeTax tax = new GuarentorIncomeTax();
            tax.setGuarentorId(guarentorId);
            tax.setYear((int) taxdtm.getValueAt(i, 0));
            tax.setTaxableIncome((double) taxdtm.getValueAt(i, 1));
            tax.setTaxPaid((double) taxdtm.getValueAt(i, 2));
            taxList.add(tax);
        }

        //get bankTable details
        DefaultTableModel bankdtm = (DefaultTableModel) bankTable.getModel();
        ArrayList<GuarentorBankers> bankerList = new ArrayList<GuarentorBankers>();

        for (int i = 0; i < bankTable.getRowCount(); i++) {
            GuarentorBankers banker = new GuarentorBankers();
            banker.setGuarentorId(guarentorId);
            banker.setBankName((String) bankdtm.getValueAt(i, 0));
            banker.setAddress((String) bankdtm.getValueAt(i, 1));
            banker.setAccountNo((String) bankdtm.getValueAt(i, 2));
            bankerList.add(banker);
        }

        try {
            ServerConnector serverConnector = ServerConnector.getServerConnector();
            GuarentorController guarentorController = serverConnector.getGuarentorController();
            GuarentorBankersController bankersController = serverConnector.getGuarentorBankersController();
            GuarentorIncomeTaxController incomeTaxController = serverConnector.getGuarentorIncomeTaxController();

            boolean res1 = guarentorController.addGuarentor(guarentor);
            if (res1) {
                boolean res2 = incomeTaxController.addIncomeTax(taxList);
                if (res2) {
                    boolean res3 = bankersController.addBankers(bankerList);
                    if (res3) {
                        JOptionPane.showMessageDialog(this, name + "'s (2nd Guarentor) details successfully added.", "Message", JOptionPane.PLAIN_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add " + name + "'s (2nd Guarentor) details.", "Message", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NotBoundException | MalformedURLException | RemoteException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddGuaranteeForm2.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGuaranteeForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGuaranteeForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGuaranteeForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGuaranteeForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddGuaranteeForm2 dialog = new AddGuaranteeForm2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNoTextField;
    private javax.swing.JLabel accountNoLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel bankAddressLabel;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JTable bankTable;
    private javax.swing.JPanel bankersPanel;
    private javax.swing.JRadioButton boarderRadioButton;
    private javax.swing.JLabel citizenshipLabel;
    private javax.swing.JTextField citizenshipTextField;
    private javax.swing.JPanel contactDeatailPanel;
    private javax.swing.JLabel guarantorIdLabel;
    private javax.swing.JTextField guarantorIdTextField;
    private javax.swing.JLabel incomeSourceLabel;
    private javax.swing.JTextField incomeSourceTextField;
    private javax.swing.JPanel incomeTaxPanel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton limitedComanyRadioButton;
    private javax.swing.JLabel maritalLabel;
    private javax.swing.ButtonGroup maritalStatusButtonGroup;
    private javax.swing.JRadioButton marriedRadioButton;
    private javax.swing.JFormattedTextField monthlyIncomeFormattedTextField;
    private javax.swing.JLabel monthlyIncomeLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JFormattedTextField nicFormattedTextField;
    private javax.swing.JLabel nicLabel;
    private javax.swing.JLabel occupationLabel;
    private javax.swing.JTextField occupationTextField;
    private javax.swing.JLabel officialAddressLabel;
    private javax.swing.JTextField officialAddressTextField;
    private javax.swing.ButtonGroup organizationTypeButtonGroup;
    private javax.swing.JLabel organizationTypeLabel;
    private javax.swing.JPanel otherDetailPanel;
    private javax.swing.JRadioButton ownerRadioButton;
    private javax.swing.JRadioButton partnershipRadioButton;
    private javax.swing.JTextField privateAddressTextField;
    private javax.swing.JLabel pvtAddressLabel;
    private javax.swing.JPanel recognitionDetailPanel;
    private javax.swing.JFormattedTextField residentDurationDaysFormattedTextField;
    private javax.swing.JLabel residentDurationDaysLabel;
    private javax.swing.JLabel residentDurationLabel;
    private javax.swing.JFormattedTextField residentDurationMonthsFormattedTextField;
    private javax.swing.JLabel residentDurationMonthsLabel;
    private javax.swing.JFormattedTextField residentDurationYearFormattedTextField;
    private javax.swing.JLabel residentDurationYearLabel;
    private javax.swing.JRadioButton soleProprietorshipRadioButton;
    private javax.swing.ButtonGroup statusInPvtButtonGroup;
    private javax.swing.JLabel statusPvtLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JFormattedTextField taxFormattedTextField;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JTable taxTable;
    private javax.swing.JFormattedTextField taxableIncomeFormattedTextField;
    private javax.swing.JLabel taxableIncomeLabel;
    private javax.swing.JFormattedTextField telNoFormattedTextField;
    private javax.swing.JLabel telNoLabel;
    private javax.swing.JRadioButton tenantRadioButton;
    private javax.swing.JRadioButton unmarriedRadioButton;
    private javax.swing.JComboBox yearComboBox;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
