/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.marketingOfficer;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import lbfinance.important.ComboSearch;
import lbfinance.serverConnector.ServerConnector;
import lbfinancecommon.controller.MarketingOfficerController;
import lbfinancecommon.model.MarketingOfficer;
import view.recoveryOfficer.*;

/**
 *
 * @author Sameera
 */
public class SearchMarketingOfficerForm extends javax.swing.JDialog {

    /**
     * Creates new form AddRecoveryOfficerForm
     */
    private JTextField search;

    public SearchMarketingOfficerForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadComboBox();
        searchComboBox.setEditable(true);
        ComboSearch comboSearch = new ComboSearch();
        comboSearch.setSearchableCombo(searchComboBox, true, "no items");
        search = (JTextField) searchComboBox.getEditor().getEditorComponent();

        search.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt) {
                String text = search.getText();
                search.setText(text);
                
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    
                    try {
                        ServerConnector serverConnector = ServerConnector.getServerConnector();
                        MarketingOfficerController marketingOfficerController = serverConnector.getMarketingOfficerController();
                        try {
                            MarketingOfficer marketingOfficers = marketingOfficerController.searchMarketingOfficer(searchComboBox.getSelectedItem() + "");
                            nameTextField.setText(marketingOfficers.getName());
                            nicFormattedTextField.setText(marketingOfficers.getNic());
                            telNoFormattedTextField.setText(marketingOfficers.getTelNo());
                            addressTextField.setText(marketingOfficers.getAddress());

                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(SearchMarketingOfficerForm.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                            Logger.getLogger(SearchMarketingOfficerForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (NotBoundException ex) {
                        Logger.getLogger(SearchMarketingOfficerForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (MalformedURLException ex) {
                        Logger.getLogger(SearchMarketingOfficerForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (RemoteException ex) {
                        Logger.getLogger(SearchMarketingOfficerForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        searchComboBox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        nicFormattedTextField = new javax.swing.JFormattedTextField();
        telNoFormattedTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Address :");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(20, 240, 50, 14);

        jLabel2.setText("Tel No :");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(20, 200, 50, 14);

        jLabel3.setText("NIC :");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(20, 160, 50, 14);

        jLabel4.setText("Name :");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(20, 120, 50, 14);

        jLabel5.setText("Search ByOfficer ID :");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(20, 80, 120, 14);
        jLayeredPane1.add(nameTextField);
        nameTextField.setBounds(90, 120, 350, 20);
        jLayeredPane1.add(addressTextField);
        addressTextField.setBounds(90, 240, 350, 20);

        searchComboBox.setEditable(true);
        searchComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComboBoxActionPerformed(evt);
            }
        });
        jLayeredPane1.add(searchComboBox);
        searchComboBox.setBounds(140, 80, 230, 20);

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton2);
        jButton2.setBounds(390, 80, 65, 23);

        try {
            nicFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########v")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jLayeredPane1.add(nicFormattedTextField);
        nicFormattedTextField.setBounds(90, 160, 130, 20);

        try {
            telNoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0##-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jLayeredPane1.add(telNoFormattedTextField);
        telNoFormattedTextField.setBounds(90, 200, 130, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchComboBoxActionPerformed
    public void loadComboBox() {
        try {
            ServerConnector serverConnector = ServerConnector.getServerConnector();
            MarketingOfficerController marketingOfficerController = serverConnector.getMarketingOfficerController();
            try {
                ArrayList<String> marketingList=marketingOfficerController.getMarketingOfficerIds();
                for (String string : marketingList) {
                    searchComboBox.addItem(string);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SearchMarketingOfficerForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(SearchMarketingOfficerForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(SearchMarketingOfficerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SearchMarketingOfficerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(SearchMarketingOfficerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRecoveryOfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRecoveryOfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRecoveryOfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRecoveryOfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SearchMarketingOfficerForm dialog = new SearchMarketingOfficerForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JFormattedTextField nicFormattedTextField;
    private javax.swing.JComboBox searchComboBox;
    private javax.swing.JFormattedTextField telNoFormattedTextField;
    // End of variables declaration//GEN-END:variables
}
