/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.main;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import lbfinance.serverConnector.ServerConnector;
import lbfinancecommon.controller.UserController;
import lbfinancecommon.model.User;
import view.client.AddLesseeForm;

/**
 *
 * @author cmjd
 */
public class MainForm extends javax.swing.JFrame {

    public static String userName = null;
    private static JLabel userDetailLabel = null;
    private static MainForm thisForm = null;

    /**
     * Creates new form MainClientForm
     */
    public MainForm() {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());

        userDetailLabel = userLabel;
        thisForm = this;

        mainViewLayeredPane.setSize(Toolkit.getDefaultToolkit().getScreenSize());

        mainBackgroundPictureLabel.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        ImageIcon icon = new ImageIcon(new ImageIcon(".\\src\\lbfinance\\images\\New Background.png").getImage().getScaledInstance(mainBackgroundPictureLabel.getWidth(), mainBackgroundPictureLabel.getHeight(), Image.SCALE_SMOOTH));
        mainBackgroundPictureLabel.setIcon(icon);
        mainBackgroundPictureLabel.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.01f));

        mainCalendar.setBackground(new Color(1.0f, 1.0f, 1.0f, 001f));

        final DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        final DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
        final Calendar c = Calendar.getInstance();
        final long miliFirst = c.getTimeInMillis();
        int interval = 1000; // 1000 ms
        new Timer(interval, new ActionListener() {
            int i = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar now = Calendar.getInstance();
                mainDateLabel.setText(dateFormat.format(now.getTime()));
                mainTimeLabel.setText(timeFormat.format(now.getTime()));
            }
        }).start();

        taskPane1.setCollapsed(true);
        taskPane1.setTitle("Leasing");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainViewLayeredPane = new javax.swing.JLayeredPane();
        logInButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        userNameTextField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        mainDateLabel = new javax.swing.JLabel();
        mainTimeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        mainCalendar = new com.toedter.calendar.JCalendar();
        mainMenuPanel = new javax.swing.JPanel();
        taskPane1 = new org.jdesktop.swingx.JXTaskPane();
        addLeasingLabel = new javax.swing.JLabel();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();
        jXTaskPane4 = new org.jdesktop.swingx.JXTaskPane();
        userLabel = new javax.swing.JLabel();
        logInWarningLowerLabel = new javax.swing.JLabel();
        logInWarningUpperLabel = new javax.swing.JLabel();
        mainBackgroundPictureLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainViewLayeredPane.setPreferredSize(new java.awt.Dimension(1366, 768));

        logInButton.setText("Log In");
        logInButton.setEnabled(false);
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        mainViewLayeredPane.add(logInButton);
        logInButton.setBounds(1280, 400, 63, 23);

        passwordLabel.setForeground(new java.awt.Color(160, 160, 160));
        passwordLabel.setText("Password :");
        mainViewLayeredPane.add(passwordLabel);
        passwordLabel.setBounds(1140, 360, 60, 14);

        passwordField.setEnabled(false);
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        mainViewLayeredPane.add(passwordField);
        passwordField.setBounds(1200, 360, 140, 20);

        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });
        mainViewLayeredPane.add(userNameTextField);
        userNameTextField.setBounds(1200, 330, 140, 20);

        userNameLabel.setForeground(new java.awt.Color(160, 160, 160));
        userNameLabel.setText("User Name :");
        mainViewLayeredPane.add(userNameLabel);
        userNameLabel.setBounds(1140, 330, 60, 14);

        mainDateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainDateLabel.setForeground(new java.awt.Color(160, 160, 160));
        mainDateLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 160, 160), 1, true));
        mainViewLayeredPane.add(mainDateLabel);
        mainDateLabel.setBounds(1230, 30, 110, 20);

        mainTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainTimeLabel.setForeground(new java.awt.Color(160, 160, 160));
        mainTimeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 160, 160), 1, true));
        mainViewLayeredPane.add(mainTimeLabel);
        mainTimeLabel.setBounds(1230, 60, 110, 20);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mainViewLayeredPane.add(jSeparator1);
        jSeparator1.setBounds(1130, 110, 10, 650);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        mainViewLayeredPane.add(jSeparator2);
        jSeparator2.setBounds(0, 106, 1360, 2);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mainViewLayeredPane.add(jSeparator3);
        jSeparator3.setBounds(290, 110, 10, 650);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        mainViewLayeredPane.add(jSeparator4);
        jSeparator4.setBounds(1130, 470, 230, 10);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        mainViewLayeredPane.add(jSeparator5);
        jSeparator5.setBounds(1130, 280, 230, 10);

        mainCalendar.setOpaque(false);
        mainViewLayeredPane.add(mainCalendar);
        mainCalendar.setBounds(1140, 120, 198, 153);

        mainMenuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));
        mainMenuPanel.setOpaque(false);

        taskPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        taskPane1.setOpaque(false);
        taskPane1.setTitle("");
        taskPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                taskPane1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                taskPane1MouseExited(evt);
            }
        });

        addLeasingLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addLeasingLabel.setText("Leasing Application");
        addLeasingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLeasingLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addLeasingLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addLeasingLabelMouseExited(evt);
            }
        });
        taskPane1.add(addLeasingLabel);

        jXTaskPane2.setOpaque(false);

        jXTaskPane3.setOpaque(false);

        jXTaskPane4.setOpaque(false);

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jXTaskPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTaskPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTaskPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTaskPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTaskPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTaskPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        mainViewLayeredPane.add(mainMenuPanel);
        mainMenuPanel.setBounds(10, 120, 270, 640);

        userLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204)));
        mainViewLayeredPane.add(userLabel);
        userLabel.setBounds(1090, 30, 120, 50);

        logInWarningLowerLabel.setForeground(new java.awt.Color(255, 102, 0));
        logInWarningLowerLabel.setText("<html>Warning!!! <br> When you log in, you will be logged off and <br>your open windows will be closed<html>");
        mainViewLayeredPane.add(logInWarningLowerLabel);
        logInWarningLowerLabel.setBounds(1140, 420, 220, 40);

        logInWarningUpperLabel.setText(" ");
        mainViewLayeredPane.add(logInWarningUpperLabel);
        logInWarningUpperLabel.setBounds(1140, 300, 210, 14);

        mainBackgroundPictureLabel.setPreferredSize(new java.awt.Dimension(1366, 768));
        mainViewLayeredPane.add(mainBackgroundPictureLabel);
        mainBackgroundPictureLabel.setBounds(0, 10, 1366, 768);

        getContentPane().add(mainViewLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taskPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskPane1MouseEntered
        taskPane1.setCollapsed(false);
    }//GEN-LAST:event_taskPane1MouseEntered

    private void taskPane1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskPane1MouseExited
        taskPane1.setCollapsed(true);
    }//GEN-LAST:event_taskPane1MouseExited

    private void addLeasingLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLeasingLabelMouseEntered
        taskPane1.setCollapsed(false);
    }//GEN-LAST:event_addLeasingLabelMouseEntered

    private void addLeasingLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLeasingLabelMouseExited
        taskPane1.setCollapsed(true);
    }//GEN-LAST:event_addLeasingLabelMouseExited

    private void addLeasingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLeasingLabelMouseClicked
        new AddLesseeForm().setVisible(true);
    }//GEN-LAST:event_addLeasingLabelMouseClicked

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        if (userNameTextField.getText() != null) {
            passwordField.setEnabled(true);
            passwordField.requestFocus();
        }
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        if (passwordField.getPassword().length > 0) {
            logInButton.setEnabled(true);
            logInButton.doClick();
        }
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        try {
            String userName = userNameTextField.getText();
            char[] ch = passwordField.getPassword();
            String password = new String(ch);
            User user = new User(userName, password, WIDTH);

            ServerConnector serverConnector = ServerConnector.getServerConnector();
            UserController userController = serverConnector.getUserController();

            int privilege = userController.searchUser(user);

            if (privilege == 1) {
                thisForm.setVisible(false);
                new MainForm().setVisible(true);
                MainForm.setUserName(userName);
                System.out.println(" Privilege 1 :" + userName);
            } else if (privilege == 2) {
                thisForm.setVisible(false);
                new MainForm().setVisible(true);
                MainForm.setUserName(userName);
                System.out.println(" Privilege 2 :" + userName);
            } else if (privilege == -1) {
                logInWarningUpperLabel.setForeground(Color.ORANGE);
                logInWarningUpperLabel.setText("Invalid username or password.");
                userNameTextField.setText(null);
                passwordField.setText(null);
                passwordField.setEnabled(false);
                logInButton.setEnabled(false);
                userNameTextField.requestFocus();
                System.out.println(" Privilege -1 :" + userName);
            }
        } catch (ClassNotFoundException | SQLException | NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    public static void setUserName(String userName) {
        MainForm.userName = userName;
        userDetailLabel.setText("<html> User : <br> " + userName + "</html>");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLeasingLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane4;
    private javax.swing.JButton logInButton;
    private javax.swing.JLabel logInWarningLowerLabel;
    private javax.swing.JLabel logInWarningUpperLabel;
    private javax.swing.JLabel mainBackgroundPictureLabel;
    private com.toedter.calendar.JCalendar mainCalendar;
    private javax.swing.JLabel mainDateLabel;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JLabel mainTimeLabel;
    private javax.swing.JLayeredPane mainViewLayeredPane;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private org.jdesktop.swingx.JXTaskPane taskPane1;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
